import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";

const directory = new URL("./", import.meta.url);
const bundlePath = new URL("./view.bundle.js", directory);
const stylePath = new URL("./view.bundle.css", directory);
const templatePath = new URL("./view.template.html", directory);
const generatedPath = new URL("./view.generated.ts", directory);

await build({
  entryPoints: [new URL("./view.ts", directory).pathname],
  outfile: bundlePath.pathname,
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "none",
});

const [template, bundle, css] = await Promise.all([
  readFile(templatePath, "utf8"),
  readFile(bundlePath, "utf8"),
  readFile(stylePath, "utf8"),
]);
const html = template
  .replace("/*__SCOUT_VIEW_STYLE__*/", () => css)
  .replace("/*__SCOUT_VIEW_BUNDLE__*/", () => bundle);
await writeFile(generatedPath, `// Generated by build-view.mjs. Do not edit.\nexport const SCOUT_VIEW_HTML = ${JSON.stringify(html)};\n`);
