import {
  buildComponentSandboxHtml as buildComponentSandboxHtmlV3,
  type SandboxMapMember,
  type SandboxMapTarget,
} from './component_v3.ts'

export type { SandboxMapMember, SandboxMapTarget }

function replaceRequired(source:string, needle:string, replacement:string, label:string){
  if(!source.includes(needle))throw new Error('Scout component sandbox v4 transform failed: '+label)
  return source.replace(needle,replacement)
}

const oldNodeCss=`.map-node{position:absolute;z-index:6;transform:translate(-50%,-50%);display:grid;place-items:center;width:25px;height:25px;border:2px solid var(--accent);background:var(--button);color:var(--button-text);font-size:12px;font-weight:800;box-shadow:0 1px 4px rgba(0,0,0,.25);pointer-events:none}.map-node.multifamily{border-radius:6px}.map-node.senior_living{border-radius:50%}.map-node.hotel{border-radius:4px 4px 10px 10px}.map-node.office{border-radius:3px}.map-node.retail{width:23px;height:23px;border-radius:4px;transform:translate(-50%,-50%) rotate(45deg)}.map-node.retail span{transform:rotate(-45deg)}.map-node.industrial{clip-path:polygon(15% 0,85% 0,100% 50%,85% 100%,15% 100%,0 50%)}.map-node.residential{border-radius:50%;width:20px;height:20px}.map-node.cluster{width:31px;height:31px;border-radius:50%;font-size:11px;background:var(--accent);color:#fff;border-color:color-mix(in srgb,var(--accent) 72%,#fff)}.map-legend{position:absolute;left:8px;top:8px;z-index:7;display:flex;gap:5px;flex-wrap:wrap;max-width:72%;padding:5px 6px;border-radius:8px;background:color-mix(in srgb,var(--card) 88%,transparent);color:var(--text);font-size:8px;line-height:1}.legend-item{display:flex;align-items:center;gap:3px;white-space:nowrap}.legend-glyph{display:grid;place-items:center;width:13px;height:13px;border:1px solid var(--accent);border-radius:4px;background:var(--button);color:var(--button-text);font-size:8px;font-weight:800}`

const newNodeCss=`.map-node{--node-rgb:78,105,86;position:absolute;z-index:6;transform:translate(-50%,-50%);display:grid;place-items:center;width:24px;height:24px;border:2px solid rgba(var(--node-rgb),.94);border-radius:50%;background:rgba(var(--node-rgb),.42);color:#fff;font-size:11px;font-weight:850;line-height:1;text-shadow:0 1px 2px rgba(0,0,0,.82);box-shadow:0 1px 4px rgba(0,0,0,.18);pointer-events:none}.map-node.multifamily{--node-rgb:36,111,121}.map-node.residential{--node-rgb:70,118,76}.map-node.senior_living{--node-rgb:171,116,39}.map-node.hotel{--node-rgb:55,92,145}.map-node.office{--node-rgb:102,80,139}.map-node.retail{--node-rgb:154,73,94}.map-node.industrial{--node-rgb:82,92,99}.map-node.size-sm{width:24px;height:24px;font-size:10px}.map-node.size-md{width:31px;height:31px;font-size:11px}.map-node.size-lg{width:38px;height:38px;font-size:12px}.map-legend{position:absolute;left:8px;top:8px;z-index:7;display:flex;gap:6px;flex-wrap:wrap;max-width:78%;padding:5px 6px;border-radius:8px;background:color-mix(in srgb,var(--card) 88%,transparent);color:var(--text);font-size:8px;line-height:1}.legend-item{display:flex;align-items:center;gap:4px;white-space:nowrap}.legend-swatch{--node-rgb:78,105,86;width:11px;height:11px;border:1.5px solid rgba(var(--node-rgb),.94);border-radius:50%;background:rgba(var(--node-rgb),.42);flex:none}.legend-swatch.multifamily{--node-rgb:36,111,121}.legend-swatch.residential{--node-rgb:70,118,76}.legend-swatch.senior_living{--node-rgb:171,116,39}.legend-swatch.hotel{--node-rgb:55,92,145}.legend-swatch.office{--node-rgb:102,80,139}.legend-swatch.retail{--node-rgb:154,73,94}.legend-swatch.industrial{--node-rgb:82,92,99}`

const oldNodeJs=`function typeGlyph(type){return({multifamily:'▦',senior_living:'+',hotel:'H',office:'▤',retail:'◆',industrial:'▰',residential:'•'})[type]||'•'}
function typeLabel(type){return({multifamily:'Multifamily',senior_living:'Senior living',hotel:'Hotel',office:'Office',retail:'Retail',industrial:'Industrial',residential:'Residential'})[type]||'Property'}
function renderLegend(){const el=document.getElementById('mapLegend');if(!el)return;if(mapTarget?.kind!=='group'||!focusMembers.length){el.hidden=true;el.innerHTML='';return}const types=[...new Set(focusMembers.map(m=>m.property_type||'residential'))].slice(0,4);el.innerHTML='';for(const type of types){const item=document.createElement('span');item.className='legend-item';const glyph=document.createElement('span');glyph.className='legend-glyph';glyph.textContent=typeGlyph(type);const label=document.createElement('span');label.textContent=typeLabel(type);item.append(glyph,label);el.appendChild(item)}el.hidden=false}
function renderGroupNodes(map,z,world,left,top){if(mapTarget?.kind!=='group'||!focusMembers.length)return;const cellSize=z<=8?46:z<=9?38:30;const cells=new Map();for(const m of focusMembers){const px=worldX(Number(m.lon))*world-left,py=worldY(Number(m.lat))*world-top;const key=Math.round(px/cellSize)+':'+Math.round(py/cellSize);const cell=cells.get(key)||{x:0,y:0,items:[]};cell.x+=px;cell.y+=py;cell.items.push(m);cells.set(key,cell)}for(const cell of cells.values()){const x=cell.x/cell.items.length,y=cell.y/cell.items.length;const node=document.createElement('span');node.style.left=x+'px';node.style.top=y+'px';if(cell.items.length>1){node.className='map-node cluster';node.textContent=String(cell.items.length);node.title=cell.items.length+' nearby portfolio properties'}else{const m=cell.items[0],type=m.property_type||'residential';node.className='map-node '+type;const glyph=document.createElement('span');glyph.textContent=typeGlyph(type);node.appendChild(glyph);node.title=m.label+' · '+typeLabel(type)}map.appendChild(node)}}`

const newNodeJs=`function typeLabel(type){return({multifamily:'Multifamily',senior_living:'Senior living',hotel:'Hotel',office:'Office',retail:'Retail',industrial:'Industrial',residential:'Residential'})[type]||'Property'}
function markerSizeClass(count){return count>=10?'size-lg':count>=4?'size-md':'size-sm'}
function renderLegend(){const el=document.getElementById('mapLegend');if(!el)return;if(mapTarget?.kind!=='group'||!focusMembers.length){el.hidden=true;el.innerHTML='';return}const types=[...new Set(focusMembers.map(m=>m.property_type||'residential'))];el.innerHTML='';for(const type of types){const item=document.createElement('span');item.className='legend-item';const swatch=document.createElement('span');swatch.className='legend-swatch '+type;swatch.setAttribute('aria-hidden','true');const label=document.createElement('span');label.textContent=typeLabel(type);item.append(swatch,label);el.appendChild(item)}el.hidden=false}
function renderGroupNodes(map,z,world,left,top){if(mapTarget?.kind!=='group'||!focusMembers.length)return;const cellSize=z<=8?46:z<=9?38:30;const cells=new Map();for(const m of focusMembers){const type=m.property_type||'residential',px=worldX(Number(m.lon))*world-left,py=worldY(Number(m.lat))*world-top;const key=type+':'+Math.round(px/cellSize)+':'+Math.round(py/cellSize);const cell=cells.get(key)||{type,x:0,y:0,items:[]};cell.x+=px;cell.y+=py;cell.items.push(m);cells.set(key,cell)}for(const cell of cells.values()){const count=cell.items.length,type=cell.type,x=cell.x/count,y=cell.y/count,node=document.createElement('span');node.style.left=x+'px';node.style.top=y+'px';node.className='map-node '+type+' '+markerSizeClass(count);node.textContent=String(count);node.title=count===1?(cell.items[0].label+' · '+typeLabel(type)):(count+' '+typeLabel(type)+' portfolio properties');map.appendChild(node)}}`

export function buildComponentSandboxHtml(targets: SandboxMapTarget[] = []) {
  let html=buildComponentSandboxHtmlV3(targets)
  html=replaceRequired(html,oldNodeCss,newNodeCss,'numbered circle CSS')
  html=replaceRequired(html,oldNodeJs,newNodeJs,'type-separated circle renderer')
  html=html.replace('Owner-only preview · group maps use typed portfolio nodes; widget state survives host remounts.','Owner-only preview · group maps use type-separated numbered circles; overlaps are preserved; widget state survives host remounts.')
  return html
}
