import {
  buildComponentSandboxHtml as buildComponentSandboxHtmlV4,
  type SandboxMapMember,
  type SandboxMapTarget,
} from './component_v4.ts'

export type { SandboxMapMember, SandboxMapTarget }

function replaceRequired(source:string, needle:string, replacement:string, label:string){
  if(!source.includes(needle))throw new Error('Scout component sandbox v5 transform failed: '+label)
  return source.replace(needle,replacement)
}

const oldNodeCss=`.map-node{--node-rgb:78,105,86;position:absolute;z-index:6;transform:translate(-50%,-50%);display:grid;place-items:center;width:24px;height:24px;border:2px solid rgba(var(--node-rgb),.94);border-radius:50%;background:rgba(var(--node-rgb),.42);color:#fff;font-size:11px;font-weight:850;line-height:1;text-shadow:0 1px 2px rgba(0,0,0,.82);box-shadow:0 1px 4px rgba(0,0,0,.18);pointer-events:none}.map-node.multifamily{--node-rgb:36,111,121}.map-node.residential{--node-rgb:70,118,76}.map-node.senior_living{--node-rgb:171,116,39}.map-node.hotel{--node-rgb:55,92,145}.map-node.office{--node-rgb:102,80,139}.map-node.retail{--node-rgb:154,73,94}.map-node.industrial{--node-rgb:82,92,99}.map-node.size-sm{width:24px;height:24px;font-size:10px}.map-node.size-md{width:31px;height:31px;font-size:11px}.map-node.size-lg{width:38px;height:38px;font-size:12px}.map-legend{position:absolute;left:8px;top:8px;z-index:7;display:flex;gap:6px;flex-wrap:wrap;max-width:78%;padding:5px 6px;border-radius:8px;background:color-mix(in srgb,var(--card) 88%,transparent);color:var(--text);font-size:8px;line-height:1}.legend-item{display:flex;align-items:center;gap:4px;white-space:nowrap}.legend-swatch{--node-rgb:78,105,86;width:11px;height:11px;border:1.5px solid rgba(var(--node-rgb),.94);border-radius:50%;background:rgba(var(--node-rgb),.42);flex:none}.legend-swatch.multifamily{--node-rgb:36,111,121}.legend-swatch.residential{--node-rgb:70,118,76}.legend-swatch.senior_living{--node-rgb:171,116,39}.legend-swatch.hotel{--node-rgb:55,92,145}.legend-swatch.office{--node-rgb:102,80,139}.legend-swatch.retail{--node-rgb:154,73,94}.legend-swatch.industrial{--node-rgb:82,92,99}`

const newNodeCss=`.map-node{--node-rgb:78,105,86;position:absolute;z-index:6;transform:translate(-50%,-50%);display:grid;place-items:center;border:2px solid rgba(var(--node-rgb),.94);border-radius:50%;background:rgba(var(--node-rgb),.42);color:#fff;box-shadow:0 1px 4px rgba(0,0,0,.18);pointer-events:none}.map-node.multifamily{--node-rgb:36,111,121}.map-node.residential{--node-rgb:70,118,76}.map-node.senior_living{--node-rgb:171,116,39}.map-node.hotel{--node-rgb:55,92,145}.map-node.office{--node-rgb:102,80,139}.map-node.retail{--node-rgb:154,73,94}.map-node.industrial{--node-rgb:82,92,99}.map-node-label{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);display:grid;place-items:center;min-width:10px;height:12px;font-size:10px;font-weight:850;line-height:1;color:#fff;text-shadow:0 1px 2px rgba(0,0,0,.9);white-space:nowrap;will-change:transform}.map-legend{position:absolute;left:8px;top:8px;z-index:7;display:flex;gap:6px;flex-wrap:wrap;max-width:78%;padding:5px 6px;border-radius:8px;background:color-mix(in srgb,var(--card) 88%,transparent);color:var(--text);font-size:8px;line-height:1}.legend-item{display:flex;align-items:center;gap:4px;white-space:nowrap}.legend-swatch{--node-rgb:78,105,86;width:11px;height:11px;border:1.5px solid rgba(var(--node-rgb),.94);border-radius:50%;background:rgba(var(--node-rgb),.42);flex:none}.legend-swatch.multifamily{--node-rgb:36,111,121}.legend-swatch.residential{--node-rgb:70,118,76}.legend-swatch.senior_living{--node-rgb:171,116,39}.legend-swatch.hotel{--node-rgb:55,92,145}.legend-swatch.office{--node-rgb:102,80,139}.legend-swatch.retail{--node-rgb:154,73,94}.legend-swatch.industrial{--node-rgb:82,92,99}`

const oldNodeJs=`function typeLabel(type){return({multifamily:'Multifamily',senior_living:'Senior living',hotel:'Hotel',office:'Office',retail:'Retail',industrial:'Industrial',residential:'Residential'})[type]||'Property'}
function markerSizeClass(count){return count>=10?'size-lg':count>=4?'size-md':'size-sm'}
function renderLegend(){const el=document.getElementById('mapLegend');if(!el)return;if(mapTarget?.kind!=='group'||!focusMembers.length){el.hidden=true;el.innerHTML='';return}const types=[...new Set(focusMembers.map(m=>m.property_type||'residential'))];el.innerHTML='';for(const type of types){const item=document.createElement('span');item.className='legend-item';const swatch=document.createElement('span');swatch.className='legend-swatch '+type;swatch.setAttribute('aria-hidden','true');const label=document.createElement('span');label.textContent=typeLabel(type);item.append(swatch,label);el.appendChild(item)}el.hidden=false}
function renderGroupNodes(map,z,world,left,top){if(mapTarget?.kind!=='group'||!focusMembers.length)return;const cellSize=z<=8?46:z<=9?38:30;const cells=new Map();for(const m of focusMembers){const type=m.property_type||'residential',px=worldX(Number(m.lon))*world-left,py=worldY(Number(m.lat))*world-top;const key=type+':'+Math.round(px/cellSize)+':'+Math.round(py/cellSize);const cell=cells.get(key)||{type,x:0,y:0,items:[]};cell.x+=px;cell.y+=py;cell.items.push(m);cells.set(key,cell)}for(const cell of cells.values()){const count=cell.items.length,type=cell.type,x=cell.x/count,y=cell.y/count,node=document.createElement('span');node.style.left=x+'px';node.style.top=y+'px';node.className='map-node '+type+' '+markerSizeClass(count);node.textContent=String(count);node.title=count===1?(cell.items[0].label+' · '+typeLabel(type)):(count+' '+typeLabel(type)+' portfolio properties');map.appendChild(node)}}`

const newNodeJs=`function typeLabel(type){return({multifamily:'Multifamily',senior_living:'Senior living',hotel:'Hotel',office:'Office',retail:'Retail',industrial:'Industrial',residential:'Residential'})[type]||'Property'}
function markerDiameter(count){if(count<=1)return 18;if(count===2)return 22;if(count===3)return 25;if(count<=5)return 29;if(count<=9)return 34;return 40}
function renderLegend(){const el=document.getElementById('mapLegend');if(!el)return;if(mapTarget?.kind!=='group'||!focusMembers.length){el.hidden=true;el.innerHTML='';return}const types=[...new Set(focusMembers.map(m=>m.property_type||'residential'))];el.innerHTML='';for(const type of types){const item=document.createElement('span');item.className='legend-item';const swatch=document.createElement('span');swatch.className='legend-swatch '+type;swatch.setAttribute('aria-hidden','true');const label=document.createElement('span');label.textContent=typeLabel(type);item.append(swatch,label);el.appendChild(item)}el.hidden=false}
function clusterTypeMarkers(items){let groups=items.map((m,i)=>({type:m.property_type||'residential',x:m._px,y:m._py,count:1,items:[m],stable:i}));let changed=true;while(changed){changed=false;let best=null;for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++){const a=groups[i],b=groups[j];if(a.type!==b.type)continue;const dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy),threshold=.82*((markerDiameter(a.count)+markerDiameter(b.count))/2);if(d<threshold&&(!best||d/threshold<best.ratio))best={i,j,ratio:d/threshold}}if(best){const a=groups[best.i],b=groups[best.j],count=a.count+b.count,merged={type:a.type,x:(a.x*a.count+b.x*b.count)/count,y:(a.y*a.count+b.y*b.count)/count,count,items:[...a.items,...b.items],stable:Math.min(a.stable,b.stable)};groups.splice(best.j,1);groups.splice(best.i,1,merged);changed=true}}return groups}
function labelCandidates(node){const digits=String(node.count).length,labelRadius=digits>1?7:6,maxShift=Math.max(0,node.r-labelRadius-2);if(maxShift<2)return[{dx:0,dy:0}];const ring=maxShift,diag=ring*.7071,angles=[[ring,0],[diag,diag],[0,ring],[-diag,diag],[-ring,0],[-diag,-diag],[0,-ring],[diag,-diag]];const rotate=node.stable%angles.length;return[{dx:0,dy:0},...angles.slice(rotate),...angles.slice(0,rotate)].map(([dx,dy])=>({dx,dy}))}
function placeResponsiveLabels(nodes){const placed=[];const ordered=[...nodes].sort((a,b)=>b.count-a.count||a.stable-b.stable);for(const node of ordered){const overlaps=nodes.some(other=>other!==node&&Math.hypot(node.x-other.x,node.y-other.y)<node.r+other.r);const candidates=overlaps?labelCandidates(node):[{dx:0,dy:0}];const labelW=Math.max(10,String(node.count).length*7),labelH=12;let best=candidates[0],bestScore=Infinity;for(let ci=0;ci<candidates.length;ci++){const c=candidates[ci],cx=node.x+c.dx,cy=node.y+c.dy;let score=ci*.0001;for(const other of nodes){if(other===node)continue;const d=Math.hypot(cx-other.x,cy-other.y),cover=Math.max(0,other.r+Math.max(labelW,labelH)*.45-d);score+=cover*cover}for(const p of placed){const ox=Math.max(0,(labelW+p.w)/2-Math.abs(cx-p.x)),oy=Math.max(0,(labelH+p.h)/2-Math.abs(cy-p.y));score+=ox*oy*8}if(score<bestScore){bestScore=score;best=c}}node.label.style.transform='translate(calc(-50% + '+best.dx.toFixed(1)+'px),calc(-50% + '+best.dy.toFixed(1)+'px))';placed.push({x:node.x+best.dx,y:node.y+best.dy,w:labelW,h:labelH})}}
function renderGroupNodes(map,z,world,left,top){if(mapTarget?.kind!=='group'||!focusMembers.length)return;const projected=focusMembers.map((m,i)=>({...m,_px:worldX(Number(m.lon))*world-left,_py:worldY(Number(m.lat))*world-top,_stable:i}));const byType=new Map();for(const m of projected){const type=m.property_type||'residential',arr=byType.get(type)||[];arr.push(m);byType.set(type,arr)}let groups=[];for(const arr of byType.values())groups.push(...clusterTypeMarkers(arr));const rendered=[];for(const g of groups){const d=markerDiameter(g.count),node=document.createElement('span'),label=document.createElement('span');node.style.left=g.x+'px';node.style.top=g.y+'px';node.style.width=d+'px';node.style.height=d+'px';node.className='map-node '+g.type;label.className='map-node-label';label.textContent=String(g.count);node.appendChild(label);node.title=g.count===1?(g.items[0].label+' · '+typeLabel(g.type)):(g.count+' '+typeLabel(g.type)+' portfolio properties');map.appendChild(node);rendered.push({x:g.x,y:g.y,r:d/2,count:g.count,type:g.type,stable:g.stable,label})}placeResponsiveLabels(rendered)}`

export function buildComponentSandboxHtml(targets: SandboxMapTarget[] = []) {
  let html=buildComponentSandboxHtmlV4(targets)
  html=replaceRequired(html,oldNodeCss,newNodeCss,'responsive numbered-circle CSS')
  html=replaceRequired(html,oldNodeJs,newNodeJs,'collision-aware circle renderer')
  html=html.replace('Owner-only preview · group maps use type-separated numbered circles; overlaps are preserved; widget state survives host remounts.','Owner-only preview · same-type circles cluster only on material collision; count labels reposition within overlapping circles; widget state survives host remounts.')
  return html
}
