import {
  buildComponentSandboxHtml as buildComponentSandboxHtmlV5,
  type SandboxMapMember,
  type SandboxMapTarget,
} from './component_v5.ts'

export type { SandboxMapMember, SandboxMapTarget }

function replaceRequired(source:string, needle:string, replacement:string, label:string){
  if(!source.includes(needle))throw new Error('Scout component sandbox v6 transform failed: '+label)
  return source.replace(needle,replacement)
}

const oldLabelCss=`.map-node-label{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);display:grid;place-items:center;min-width:10px;height:12px;font-size:10px;font-weight:850;line-height:1;color:#fff;text-shadow:0 1px 2px rgba(0,0,0,.9);white-space:nowrap;will-change:transform}`
const newLabelCss=`.map-node-label{--label-x:0px;--label-y:0px;--label-font:10px;position:absolute;left:50%;top:50%;transform:translate(-50%,-50%) translate(var(--label-x),var(--label-y));display:grid;place-items:center;min-width:10px;height:1em;font-size:var(--label-font);font-weight:850;line-height:1;color:#fff;text-shadow:0 0 1px rgba(0,0,0,.96),0 1px 2px rgba(0,0,0,.88);white-space:nowrap;will-change:transform}`

const oldClusterJs=`function clusterTypeMarkers(items){let groups=items.map((m,i)=>({type:m.property_type||'residential',x:m._px,y:m._py,count:1,items:[m],stable:i}));let changed=true;while(changed){changed=false;let best=null;for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++){const a=groups[i],b=groups[j];if(a.type!==b.type)continue;const dx=a.x-b.x,dy=a.y-b.y,d=Math.hypot(dx,dy),threshold=.82*((markerDiameter(a.count)+markerDiameter(b.count))/2);if(d<threshold&&(!best||d/threshold<best.ratio))best={i,j,ratio:d/threshold}}if(best){const a=groups[best.i],b=groups[best.j],count=a.count+b.count,merged={type:a.type,x:(a.x*a.count+b.x*b.count)/count,y:(a.y*a.count+b.y*b.count)/count,count,items:[...a.items,...b.items],stable:Math.min(a.stable,b.stable)};groups.splice(best.j,1);groups.splice(best.i,1,merged);changed=true}}return groups}`
const newClusterJs=`const PROPERTY_TYPE_ORDER=['multifamily','senior_living','hotel','office','retail','industrial','residential']
function propertyTypeRank(type){const rank=PROPERTY_TYPE_ORDER.indexOf(type);return rank<0?PROPERTY_TYPE_ORDER.length:rank}
function stableMemberKey(m){return String(m.property_type||'residential')+'|'+Number(m.lat).toFixed(7)+'|'+Number(m.lon).toFixed(7)+'|'+String(m.key||m.label||'')}
function markerRadius(count){return markerDiameter(count)/2}
function clusterSameTypeByCollision(items){let groups=[...items].sort((a,b)=>stableMemberKey(a).localeCompare(stableMemberKey(b))).map(m=>({type:m.property_type||'residential',x:m._px,y:m._py,count:1,items:[m],stableKey:stableMemberKey(m)}));while(true){let best=null;for(let i=0;i<groups.length;i++)for(let j=i+1;j<groups.length;j++){const a=groups[i],b=groups[j],threshold=.85*(markerRadius(a.count)+markerRadius(b.count)),distance=Math.hypot(a.x-b.x,a.y-b.y);if(distance>=threshold)continue;const ratio=threshold>0?distance/threshold:0,pairKey=a.stableKey<b.stableKey?a.stableKey+'||'+b.stableKey:b.stableKey+'||'+a.stableKey;if(!best||ratio<best.ratio-1e-9||(Math.abs(ratio-best.ratio)<=1e-9&&pairKey<best.pairKey))best={i,j,ratio,pairKey}}if(!best)break;const a=groups[best.i],b=groups[best.j],count=a.count+b.count,items=[...a.items,...b.items].sort((x,y)=>stableMemberKey(x).localeCompare(stableMemberKey(y))),merged={type:a.type,x:(a.x*a.count+b.x*b.count)/count,y:(a.y*a.count+b.y*b.count)/count,count,items,stableKey:items.map(stableMemberKey).join('||')};groups.splice(best.j,1);groups.splice(best.i,1,merged)}return groups.sort((a,b)=>a.stableKey.localeCompare(b.stableKey))}`

const oldLabelCandidatesJs=`function labelCandidates(node){const digits=String(node.count).length,labelRadius=digits>1?7:6,maxShift=Math.max(0,node.r-labelRadius-2);if(maxShift<2)return[{dx:0,dy:0}];const ring=maxShift,diag=ring*.7071,angles=[[ring,0],[diag,diag],[0,ring],[-diag,diag],[-ring,0],[-diag,-diag],[0,-ring],[diag,-diag]];const rotate=node.stable%angles.length;return[{dx:0,dy:0},...angles.slice(rotate),...angles.slice(0,rotate)].map(([dx,dy])=>({dx,dy}))}`
const newLabelCandidatesJs=`function markerFontSize(diameter,count){let size=diameter<=18?10:diameter<=25?11:diameter<=34?12:13;if(count>=10&&diameter<40)size-=1;return size}
function labelMetrics(node){const font=markerFontSize(node.r*2,node.count),digits=String(node.count).length,w=Math.max(10,digits*font*.60+2),h=font;return{font,w,h}}
function labelCandidatePositions(node){const r=node.r;return[{dx:0,dy:0},{dx:0,dy:-.22*r},{dx:0,dy:.22*r},{dx:-.22*r,dy:0},{dx:.22*r,dy:0},{dx:-.16*r,dy:-.16*r},{dx:.16*r,dy:-.16*r},{dx:-.16*r,dy:.16*r},{dx:.16*r,dy:.16*r}]}`

const oldPlaceLabelsJs=`function placeResponsiveLabels(nodes){const placed=[];const ordered=[...nodes].sort((a,b)=>b.count-a.count||a.stable-b.stable);for(const node of ordered){const overlaps=nodes.some(other=>other!==node&&Math.hypot(node.x-other.x,node.y-other.y)<node.r+other.r);const candidates=overlaps?labelCandidates(node):[{dx:0,dy:0}];const labelW=Math.max(10,String(node.count).length*7),labelH=12;let best=candidates[0],bestScore=Infinity;for(let ci=0;ci<candidates.length;ci++){const c=candidates[ci],cx=node.x+c.dx,cy=node.y+c.dy;let score=ci*.0001;for(const other of nodes){if(other===node)continue;const d=Math.hypot(cx-other.x,cy-other.y),cover=Math.max(0,other.r+Math.max(labelW,labelH)*.45-d);score+=cover*cover}for(const p of placed){const ox=Math.max(0,(labelW+p.w)/2-Math.abs(cx-p.x)),oy=Math.max(0,(labelH+p.h)/2-Math.abs(cy-p.y));score+=ox*oy*8}if(score<bestScore){bestScore=score;best=c}}node.label.style.transform='translate(calc(-50% + '+best.dx.toFixed(1)+'px),calc(-50% + '+best.dy.toFixed(1)+'px))';placed.push({x:node.x+best.dx,y:node.y+best.dy,w:labelW,h:labelH})}}`
const newPlaceLabelsJs=`function rectIntersectionArea(a,b){const w=Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left)),h=Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));return w*h}
function labelRect(node,candidate,metrics){const cx=node.x+candidate.dx,cy=node.y+candidate.dy;return{cx,cy,left:cx-metrics.w/2,right:cx+metrics.w/2,top:cy-metrics.h/2,bottom:cy+metrics.h/2,w:metrics.w,h:metrics.h}}
function scoreLabelPosition(node,candidate,allCircles,placedLabels,metrics,index){const rect=labelRect(node,candidate,metrics),corners=[[rect.left,rect.top],[rect.right,rect.top],[rect.left,rect.bottom],[rect.right,rect.bottom]],innerRadius=Math.max(0,node.r-.25);let maxOwnDistance=0;for(const [x,y] of corners)maxOwnDistance=Math.max(maxOwnDistance,Math.hypot(x-node.x,y-node.y));let score=index*.001+Math.hypot(candidate.dx,candidate.dy)*.28;if(maxOwnDistance>innerRadius)score+=100000+(maxOwnDistance-innerRadius)*10000;else{const edgeClearance=innerRadius-maxOwnDistance;if(edgeClearance<1.25)score+=(1.25-edgeClearance)*(1.25-edgeClearance)*8}const samples=[[rect.cx,rect.cy],[rect.left,rect.top],[rect.right,rect.top],[rect.left,rect.bottom],[rect.right,rect.bottom],[rect.cx,rect.top],[rect.cx,rect.bottom],[rect.left,rect.cy],[rect.right,rect.cy]];for(const other of allCircles){if(other===node)continue;let covered=0;for(const [sx,sy] of samples)if(Math.hypot(sx-other.x,sy-other.y)<other.r)covered++;if(covered){score+=covered*20;if(Math.hypot(rect.cx-other.x,rect.cy-other.y)<other.r)score+=140;const circleOverlap=Math.max(0,node.r+other.r-Math.hypot(node.x-other.x,node.y-other.y));score+=circleOverlap*covered*.55}}for(const placed of placedLabels){const area=rectIntersectionArea(rect,placed);if(area>0)score+=area*18}return score}
function resolveLabelPositions(nodes){const placed=[];const ordered=[...nodes].sort((a,b)=>b.count-a.count||propertyTypeRank(a.type)-propertyTypeRank(b.type)||a.stableKey.localeCompare(b.stableKey));for(const node of ordered){const metrics=labelMetrics(node),overlaps=nodes.some(other=>other!==node&&Math.hypot(node.x-other.x,node.y-other.y)<node.r+other.r),candidates=overlaps?labelCandidatePositions(node):[{dx:0,dy:0}];let best=candidates[0],bestScore=Infinity;for(let i=0;i<candidates.length;i++){const candidate=candidates[i],score=scoreLabelPosition(node,candidate,nodes,placed,metrics,i);if(score<bestScore-1e-9){bestScore=score;best=candidate}}node.label.style.setProperty('--label-x',best.dx.toFixed(2)+'px');node.label.style.setProperty('--label-y',best.dy.toFixed(2)+'px');node.label.style.setProperty('--label-font',metrics.font+'px');const rect=labelRect(node,best,metrics);placed.push(rect)}}`

const oldRenderGroupJs=`function renderGroupNodes(map,z,world,left,top){if(mapTarget?.kind!=='group'||!focusMembers.length)return;const projected=focusMembers.map((m,i)=>({...m,_px:worldX(Number(m.lon))*world-left,_py:worldY(Number(m.lat))*world-top,_stable:i}));const byType=new Map();for(const m of projected){const type=m.property_type||'residential',arr=byType.get(type)||[];arr.push(m);byType.set(type,arr)}let groups=[];for(const arr of byType.values())groups.push(...clusterTypeMarkers(arr));const rendered=[];for(const g of groups){const d=markerDiameter(g.count),node=document.createElement('span'),label=document.createElement('span');node.style.left=g.x+'px';node.style.top=g.y+'px';node.style.width=d+'px';node.style.height=d+'px';node.className='map-node '+g.type;label.className='map-node-label';label.textContent=String(g.count);node.appendChild(label);node.title=g.count===1?(g.items[0].label+' · '+typeLabel(g.type)):(g.count+' '+typeLabel(g.type)+' portfolio properties');map.appendChild(node);rendered.push({x:g.x,y:g.y,r:d/2,count:g.count,type:g.type,stable:g.stable,label})}placeResponsiveLabels(rendered)}`
const newRenderGroupJs=`function renderGroupNodes(map,z,world,left,top){if(mapTarget?.kind!=='group'||!focusMembers.length)return;const projected=focusMembers.map(m=>({...m,_px:worldX(Number(m.lon))*world-left,_py:worldY(Number(m.lat))*world-top}));const byType=new Map();for(const m of projected){const type=m.property_type||'residential',arr=byType.get(type)||[];arr.push(m);byType.set(type,arr)}let groups=[];for(const type of [...byType.keys()].sort((a,b)=>propertyTypeRank(a)-propertyTypeRank(b)||a.localeCompare(b)))groups.push(...clusterSameTypeByCollision(byType.get(type)));const rendered=[];for(const g of groups){const d=markerDiameter(g.count),node=document.createElement('span'),label=document.createElement('span');node.style.left=g.x+'px';node.style.top=g.y+'px';node.style.width=d+'px';node.style.height=d+'px';node.className='map-node '+g.type;label.className='map-node-label';label.textContent=String(g.count);node.appendChild(label);node.title=g.count===1?(g.items[0].label+' · '+typeLabel(g.type)):(g.count+' '+typeLabel(g.type)+' portfolio properties');map.appendChild(node);rendered.push({x:g.x,y:g.y,r:d/2,count:g.count,type:g.type,stableKey:g.stableKey,label})}resolveLabelPositions(rendered)}`

export function buildComponentSandboxHtml(targets: SandboxMapTarget[] = []) {
  let html=buildComponentSandboxHtmlV5(targets)
  html=replaceRequired(html,oldLabelCss,newLabelCss,'CSS-variable internal label offsets')
  html=replaceRequired(html,oldClusterJs,newClusterJs,'0.85 collision clustering with deterministic ties')
  html=replaceRequired(html,oldLabelCandidatesJs,newLabelCandidatesJs,'responsive label metrics and candidates')
  html=replaceRequired(html,oldPlaceLabelsJs,newPlaceLabelsJs,'overlap-aware deterministic label scoring')
  html=replaceRequired(html,oldRenderGroupJs,newRenderGroupJs,'stable type-separated group rendering')
  html=html.replace('Owner-only preview · same-type circles cluster only on material collision; count labels reposition within overlapping circles; widget state survives host remounts.','Owner-only preview · count-scaled same-type circles merge only at 0.85 screen-space collision; count labels move only within their own circles; widget state survives host remounts.')
  return html
}
