import assert from 'node:assert/strict'
import { build } from 'esbuild'
import { readFile } from 'node:fs/promises'

const directory = new URL('./', import.meta.url)
const result = await build({
  entryPoints: [new URL('view.ts', directory).pathname],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  minify: true,
  legalComments: 'none',
  write: false,
})
const [template, generated] = await Promise.all([
  readFile(new URL('view.template.html', directory), 'utf8'),
  readFile(new URL('view.generated.ts', directory), 'utf8'),
])
const bundle = result.outputFiles[0].text
const html = template.replace('/*__SCOUT_VIEW_BUNDLE__*/', () => bundle)
const expected = `// Generated by build-view.mjs. Do not edit.\nexport const SCOUT_VIEW_HTML = ${JSON.stringify(html)};\n`
assert.equal(generated, expected, 'view.generated.ts is stale; run npm run build and commit the regenerated View')
console.log('Scout generated View parity check passed.')
