import type { ScoutSandboxHotelPortfolioMap } from './hotel_portfolio_map_model.ts'
import { buildScoutHotelPortfolioRasterFrame, type ScoutHotelPortfolioRasterFrameOptions } from './hotel_portfolio_map_renderer.ts'
const DEFAULT_TIMEOUT_MS=7000
const PNG_DATA_URL_PREFIX='data:image/png;base64,'
const FAMILY={marriott:{label:'Marriott family',color:'#3769b2'},hilton:{label:'Hilton family',color:'#3f7f78'},ihg:{label:'IHG family',color:'#b96a2d'},other:{label:'Other',color:'#7656a8'}} as const
type Family=keyof typeof FAMILY
function brandFamily(brands:string[]):Family{const text=brands.join(' ').toLowerCase();if(/marriott|courtyard|residence inn|springhill|fairfield|westin|sheraton/.test(text))return'marriott';if(/hilton|hampton|tru|homewood|embassy/.test(text))return'hilton';if(/holiday inn|ihg|crowne plaza/.test(text))return'ihg';return'other'}
async function decodeEmbeddedRasterTile(dataUrl:string){if(!dataUrl.startsWith(PNG_DATA_URL_PREFIX))throw new Error('Scout embedded raster tile is invalid');const binary=atob(dataUrl.slice(PNG_DATA_URL_PREFIX.length)),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return await createImageBitmap(new Blob([bytes],{type:'image/png'}))}
export type ScoutHotelPortfolioMapMountOptions=ScoutHotelPortfolioRasterFrameOptions&{attributionLabel:string;attributionUrl:string;timeoutMs?:number;embeddedTiles?:Record<string,string>;onError?:(error:Error)=>void;onReady?:()=>void}
export function mountScoutHotelPortfolioMap(container:HTMLElement,data:ScoutSandboxHotelPortfolioMap,options:ScoutHotelPortfolioMapMountOptions){let destroyed=false,generation=0,timeout:ReturnType<typeof setTimeout>|null=null,lastW=-1,lastH=-1;const clear=()=>{if(timeout!==null){clearTimeout(timeout);timeout=null}};const render=(force=false)=>{if(destroyed)return;const frame=buildScoutHotelPortfolioRasterFrame(data,container.clientWidth,container.clientHeight,options);if(!force&&frame.width===lastW&&frame.height===lastH)return;lastW=frame.width;lastH=frame.height;clear();generation++;const g=generation;container.replaceChildren();let loaded=0,settled=0,ready=false;const ok=()=>{if(destroyed||g!==generation||ready)return;ready=true;clear();options.onReady?.()};const bad=()=>{if(destroyed||g!==generation||ready)return;clear();options.onError?.(new Error('Scout raster tiles did not load'))};const embedded=frame.tiles.length>0&&frame.tiles.every(t=>options.embeddedTiles?.[t.url]);if(embedded){const canvas=document.createElement('canvas');canvas.width=frame.width;canvas.height=frame.height;canvas.style.position='absolute';canvas.style.inset='0';canvas.style.width=`${frame.width}px`;canvas.style.height=`${frame.height}px`;container.appendChild(canvas);const ctx=canvas.getContext('2d');if(!ctx){bad();return}void Promise.allSettled(frame.tiles.map(async t=>{const bitmap=await decodeEmbeddedRasterTile(options.embeddedTiles![t.url]);if(!destroyed&&g===generation){ctx.drawImage(bitmap,t.left,t.top,256,256);loaded++}bitmap.close()})).then(()=>{settled=frame.tiles.length;loaded>0?ok():bad()})}else{for(const t of frame.tiles){const image=document.createElement('img');image.alt='';image.draggable=false;image.decoding='async';image.loading='eager';image.referrerPolicy='origin';image.src=t.url;image.style.left=`${t.left}px`;image.style.top=`${t.top}px`;image.addEventListener('load',()=>{if(destroyed||g!==generation)return;loaded++;settled++;if(loaded===1)ok()},{once:true});image.addEventListener('error',()=>{if(destroyed||g!==generation)return;settled++;if(settled===frame.tiles.length&&loaded===0)bad()},{once:true});container.appendChild(image)}}
const families=new Set<Family>();for(const m of frame.markers){const family=brandFamily(m.brands);families.add(family);const info=FAMILY[family],marker=document.createElement('span');marker.className='scout-portfolio-marker';marker.style.left=`${m.left}px`;marker.style.top=`${m.top}px`;marker.style.setProperty('--scout-portfolio-marker-color',info.color);marker.style.backgroundColor=info.color;marker.title=`${m.name} · ${m.brands.join(' / ')} · resolved building`;marker.setAttribute('aria-hidden','true');container.appendChild(marker)}
const legend=document.createElement('span');legend.className='scout-portfolio-legend';legend.setAttribute('aria-hidden','true');for(const key of ['marriott','hilton','ihg','other'] as Family[]){if(!families.has(key))continue;const info=FAMILY[key],item=document.createElement('span');item.className='scout-portfolio-legend-item';const swatch=document.createElement('span');swatch.className='scout-portfolio-legend-swatch';swatch.style.backgroundColor=info.color;const text=document.createElement('span');text.textContent=info.label;item.append(swatch,text);legend.appendChild(item)}const unresolved=data.member_count-data.resolved_member_count;if(unresolved>0){const status=document.createElement('span');status.className='scout-portfolio-legend-status';status.textContent=`${unresolved} roster site${unresolved===1?'':'s'} unresolved · not mapped`;legend.appendChild(status)}container.appendChild(legend)
const attr=document.createElement('span');attr.className='scout-map-attribution';const link=document.createElement('a');link.href=options.attributionUrl;link.target='_blank';link.rel='noreferrer';link.textContent=options.attributionLabel;attr.appendChild(link);container.appendChild(attr);if(frame.tiles.length===0){bad();return}timeout=setTimeout(()=>loaded>0?ok():bad(),options.timeoutMs??DEFAULT_TIMEOUT_MS)};render(true);return{resize(){render(false)},destroy(){if(destroyed)return;destroyed=true;generation++;clear();container.replaceChildren()}}}
