import { readFile } from 'node:fs/promises'
import assert from 'node:assert/strict'
import { build } from 'esbuild'
const d=new URL('./',import.meta.url)
const modelSource=await readFile(new URL('hotel_portfolio_map_model.ts',d),'utf8'),mountSource=await readFile(new URL('hotel_portfolio_map_mount.ts',d),'utf8')
assert.ok(modelSource.includes('commonwealth-hotels-managed-portfolio'));assert.ok(modelSource.includes('confidenceValue==null'));assert.ok(mountSource.includes('Marriott family'));assert.ok(mountSource.includes('Hilton family'))
const resolved=[['Courtyard Cincinnati Airport',['Courtyard by Marriott'],[-84.628490281,39.052913717]],['Hampton Inn Cincinnati Airport',['Hampton by Hilton'],[-84.635182438,39.015264895]],['Hampton Inn Louisville Airport',['Hampton by Hilton'],[-85.743168701,38.190898942]],['Residence Inn Louisville Airport',['Residence Inn by Marriott'],[-85.744392935,38.190277203]],['SpringHill Suites Louisville Airport',['SpringHill Suites by Marriott'],[-85.74172902,38.190708967]]]
const unresolved=[['Holiday Inn Express & Suites Cincinnati',['Holiday Inn Express & Suites']],['Residence Inn Cincinnati Airport',['Residence Inn by Marriott']],['Tru by Hilton Louisville Airport',['Tru by Hilton']]]
const members=[...resolved.map(([name,brands,coordinates],i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,name,address:'address',city:'city',state_code:'KY',brands,point:{type:'Point',coordinates},resolution_state:'single_building_resolved',resolved_building_count:1,link_confidence:.99,within_pilot_radius:true,observed_at:'2026-09-07T20:24:19.916463+00:00'})),...unresolved.map(([name,brands],i)=>({id:`00000000-0000-4000-8000-${String(i+20).padStart(12,'0')}`,name,address:'address',city:'city',state_code:'KY',brands,point:{type:'unresolved'},resolution_state:'unresolved',resolved_building_count:0,within_pilot_radius:true,observed_at:'2026-09-07T20:24:19.916463+00:00'}))]
const raw={contract_version:'hotel_management_portfolio_map_v1',account_name:'Commonwealth Hotels',organization_id:'6513f69a-bb53-4706-854b-bf9f7ba3064b',scope:'documented_operating_roster',source_slug:'commonwealth-hotels-managed-portfolio',relationship:'manages',target_kind:'site_member',map_semantics:'documented_operating_hotel_portfolio',evidence_boundary:'first-party hotel-management roster plus resolved building crosswalks',generated_at:'2026-09-15T01:00:00Z',contact_route_available:true,operations_route_available:true,procurement_route_available:true,vendor_route_proven:false,current_need_scan_complete:true,members}
const mb=await build({entryPoints:[new URL('hotel_portfolio_map_model.ts',d).pathname],bundle:true,format:'esm',platform:'node',target:'node24',write:false});const mod=await import(`data:text/javascript;base64,${Buffer.from(mb.outputFiles[0].text).toString('base64')}`);const normalized=mod.normalizeScoutSandboxHotelPortfolioMap(raw);assert.ok(normalized);assert.equal(normalized.member_count,8);assert.equal(normalized.resolved_member_count,5);assert.equal(normalized.resolved_building_count,5);assert.equal(normalized.members.filter(x=>x.link_confidence===null).length,3)
const bad=structuredClone(raw);delete bad.members[0].link_confidence;assert.equal(mod.normalizeScoutSandboxHotelPortfolioMap(bad),null)
const rb=await build({entryPoints:[new URL('hotel_portfolio_map_renderer.ts',d).pathname],bundle:true,format:'esm',platform:'node',target:'node24',write:false});const ren=await import(`data:text/javascript;base64,${Buffer.from(rb.outputFiles[0].text).toString('base64')}`);const frame=ren.buildScoutHotelPortfolioRasterFrame(normalized,456,210,{tileUrlTemplate:'https://tile/{z}/{x}/{y}.png'});assert.equal(frame.zoom,7);assert.equal(frame.tiles.length,6);assert.equal(frame.markers.length,5);assert.deepEqual(frame.tiles.map(x=>`${x.z}/${x.x}/${x.y}`).sort(),['7/32/48','7/32/49','7/33/48','7/33/49','7/34/48','7/34/49']);const narrow=ren.buildScoutHotelPortfolioRasterFrame(normalized,280,210,{tileUrlTemplate:'https://tile/{z}/{x}/{y}.png'});assert.equal(narrow.zoom,7);assert.deepEqual(narrow.tiles.map(x=>`${x.z}/${x.x}/${x.y}`).sort(),['7/33/48','7/33/49','7/34/48','7/34/49']);console.log('Scout hotel portfolio checks passed: 8 roster, 5 mapped, zoom 7.')
