import type { ScoutSandboxPortfolioType } from '../_shared/scout_sandbox_manifest.ts'
import { mountScoutWaterUtilityPortfolioMap } from './water_portfolio_map_mount.ts'
import { mountScoutDealershipPortfolioMap } from './dealership_portfolio_map_mount.ts'
import { mountScoutHotelPortfolioMap } from './hotel_portfolio_map_mount.ts'
import { mountScoutSchoolDistrictPortfolioMap } from './school_district_portfolio_map_mount.ts'
import { mountScoutMunicipalFacilitiesPortfolioMap } from './municipal_facilities_portfolio_map_mount.ts'
import { SCOUT_SPINE_GROUPED_PORTFOLIO_TYPES, type ScoutSpineGroupedPortfolioType } from '../_shared/scout_sandbox_spine_grouped_portfolio_config.ts'
import { scoutSpineGroupedPortfolioPresentation } from './spine_grouped_portfolio_model.ts'
import { mountScoutSpineGroupedPortfolioMap } from './spine_grouped_portfolio_map_mount.ts'

type Presentation = { title:string; tier:string; meta:string; address:string; summary:string; guardrail:string; state:string }
function observed(value:string){const date=new Date(value);if(Number.isNaN(date.valueOf()))return value;return new Intl.DateTimeFormat('en-US',{year:'numeric',month:'short',day:'numeric',timeZone:'UTC'}).format(date)}
function number(value:number){return new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(value)}
function money(value:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value)}
const groupedViewImplementations=Object.fromEntries(SCOUT_SPINE_GROUPED_PORTFOLIO_TYPES.map((type)=>[type,{mount:mountScoutSpineGroupedPortfolioMap,presentation:scoutSpineGroupedPortfolioPresentation}])) as Record<ScoutSpineGroupedPortfolioType,any>
export const SCOUT_SANDBOX_PORTFOLIO_VIEW_IMPLEMENTATIONS={
  water_utility_portfolio:{mount:mountScoutWaterUtilityPortfolioMap,presentation:(opportunity:any):Presentation=>({title:opportunity.name,tier:'Portfolio evidence',meta:`${number(opportunity.member_count)} documented tank records  •  Kentucky WRIS source modified ${observed(opportunity.source_modified_at)}`,address:`PWSID ${opportunity.pwsid}`,summary:`${number(opportunity.not_in_service_count)} documented not in service  •  ${number(opportunity.historical_project_signal_count)} historical rehab-linked records  •  ${opportunity.why_investigate}`,guardrail:`Scout guardrail: ${opportunity.guardrail}`,state:`Scout portfolio ready: ${opportunity.name}`})},
  dealership_group_portfolio:{mount:mountScoutDealershipPortfolioMap,presentation:(opportunity:any):Presentation=>{const route=opportunity.operations_route_available||opportunity.procurement_route_available?'Operations / procurement route available':opportunity.contact_route_available?'Contact route available; operations / procurement route unresolved':'Account route unresolved';return{title:opportunity.name,tier:'Portfolio evidence',meta:`${number(opportunity.member_count)} documented operating dealership sites  •  First-party roster observed ${observed(opportunity.observed_at)}`,address:'Kentucky pilot portfolio',summary:`${number(opportunity.resolved_member_count)} sites physically crosswalked  •  ${number(opportunity.resolved_building_count)} resolved buildings  •  ${number(opportunity.unresolved_member_count)} roster sites not mapped  •  ${route}  •  ${opportunity.why_investigate}`,guardrail:`Scout guardrail: ${opportunity.guardrail}`,state:`Scout portfolio ready: ${opportunity.name}`}}},
  hotel_management_portfolio:{mount:mountScoutHotelPortfolioMap,presentation:(opportunity:any):Presentation=>{const route=opportunity.operations_route_available&&opportunity.procurement_route_available?'Operations + procurement routes available':opportunity.contact_route_available?'Contact route available; account purchasing route incomplete':'Account route unresolved',vendor=opportunity.vendor_route_proven?'vendor route documented':'vendor route not yet proven';return{title:opportunity.name,tier:'Portfolio evidence',meta:`${number(opportunity.member_count)} documented operating hotels  •  First-party management roster observed ${observed(opportunity.observed_at)}`,address:'Kentucky pilot hotel portfolio',summary:`${number(opportunity.resolved_member_count)} hotels physically crosswalked  •  ${number(opportunity.resolved_building_count)} resolved buildings  •  ${number(opportunity.unresolved_member_count)} roster sites not mapped  •  ${route}; ${vendor}  •  ${opportunity.why_investigate}`,guardrail:`Scout guardrail: ${opportunity.guardrail}`,state:`Scout portfolio ready: ${opportunity.name}`}}},
  school_district_portfolio:{mount:mountScoutSchoolDistrictPortfolioMap,presentation:(opportunity:any):Presentation=>({title:opportunity.name,tier:'Portfolio evidence',meta:`${number(opportunity.member_count)} documented public schools  •  NCES ${opportunity.school_year} roster / DLGF capital-plan evidence`,address:'Scott County, Indiana  •  DLGF unit 7255',summary:`${money(opportunity.roof_project_estimated_cost)} district-level Roof Project  •  ${opportunity.roof_project_start_text}–${opportunity.roof_project_end_text}  •  No campus identified in source  •  ${opportunity.why_investigate}`,guardrail:`Scout guardrail: ${opportunity.guardrail}`,state:`Scout portfolio ready: ${opportunity.name}`})},
  municipal_facilities_portfolio:{mount:mountScoutMunicipalFacilitiesPortfolioMap,presentation:(opportunity:any):Presentation=>({title:opportunity.name,tier:'Portfolio evidence',meta:`${number(opportunity.member_count)} documented civic locations  •  ${number(opportunity.signaled_member_count)} member-specific Scout signal`,address:'Louisville / Jefferson County, Kentucky',summary:`Judicial Center cleaning proxy: ${opportunity.signal_strength} · ${Math.round(opportunity.signal_confidence*100)}% confidence  •  Procurement and durable contact routing available at account level; no open solicitation implied  •  ${opportunity.why_investigate}`,guardrail:`Scout guardrail: ${opportunity.guardrail}`,state:`Scout portfolio ready: ${opportunity.name}`})},
  ...groupedViewImplementations,
} as const satisfies Record<ScoutSandboxPortfolioType,{mount:any;presentation:(opportunity:any)=>Presentation}>
export function scoutSandboxPortfolioViewImplementation(type:ScoutSandboxPortfolioType){return SCOUT_SANDBOX_PORTFOLIO_VIEW_IMPLEMENTATIONS[type] as any}
export function assertScoutSandboxPortfolioViewImplementationCoverage(){return Object.keys(SCOUT_SANDBOX_PORTFOLIO_VIEW_IMPLEMENTATIONS).sort().join('|')}
