import type { SandboxContactCard, SandboxContactRoute, SandboxMapTarget } from './component_v13.ts'

const encoder=new TextEncoder()
const decoder=new TextDecoder()
const VCARD_DOWNLOAD_TTL_MS=15*60*1000

function b64urlEncode(bytes:Uint8Array){let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlDecode(value:string){const padded=value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4);const binary=atob(padded);return Uint8Array.from(binary,c=>c.charCodeAt(0))}

async function downloadKey(secret:string){const material=await crypto.subtle.digest('SHA-256',encoder.encode('scout-component-vcard-v1:'+secret));return crypto.subtle.importKey('raw',material,{name:'AES-GCM'},false,['encrypt','decrypt'])}

async function sealPayload(payload:{exp:number;filename:string;content:string},secret:string){const iv=crypto.getRandomValues(new Uint8Array(12)),key=await downloadKey(secret),plaintext=encoder.encode(JSON.stringify(payload)),ciphertext=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plaintext));return b64urlEncode(iv)+'.'+b64urlEncode(ciphertext)}

async function openPayload(token:string,secret:string){const [ivPart,cipherPart,...rest]=token.split('.');if(!ivPart||!cipherPart||rest.length)return null;try{const iv=b64urlDecode(ivPart),cipher=b64urlDecode(cipherPart),key=await downloadKey(secret),plaintext=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,cipher),parsed=JSON.parse(decoder.decode(plaintext));if(!parsed||typeof parsed.exp!=='number'||parsed.exp<Date.now()||typeof parsed.filename!=='string'||typeof parsed.content!=='string')return null;if(parsed.filename.length>120||parsed.content.length>12000)return null;return parsed as {exp:number;filename:string;content:string}}catch{return null}}

function safeText(value:unknown,max=400){return typeof value==='string'?value.trim().slice(0,max):''}
function httpUrl(value:unknown){const text=safeText(value,600);return /^https?:\/\//i.test(text)?text:''}
function escapeVcard(value:unknown){return String(value??'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,')}
function filenameFor(name:string){const base=name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70)||'scout-contact';return base+'.vcf'}

function namedRouteIdentity(route:SandboxContactRoute){const label=safeText(route.label,220),value=safeText(route.value,800);let match=value.match(/^(?:ask for|call[^.]*?and ask for)\s+([^,]+),\s+(.+?)(?:\s+via\b|\.|$)/i);if(match){const rawName=match[1].trim();if(!/\bor\b/i.test(rawName))return{name:rawName,title:match[2].trim()}}const parts=label.split(/\s+[—–]\s+/);if(parts.length===2){const left=parts[0].trim(),right=parts[1].trim();if(right.split(/\s+/).length>=2&&!/routing|request|vendor|facilit|operations route|procurement route/i.test(right))return{name:right,title:left}}return null}

function personCardFromRoute(card:SandboxContactCard,route:SandboxContactRoute):SandboxContactCard|null{const identity=namedRouteIdentity(route);if(!identity)return null;return{lead_key:String(card.lead_key||'lead')+':'+String(route.key||identity.name),subject_name:identity.name,organization_name:card.organization_name||card.subject_name||null,organization_type:card.organization_type||null,site_name:card.site_name||null,address:card.address||null,website_url:card.website_url||null,role_label:identity.title||null,resolution_status:'named_routing_contact',enrichment_status:'partial',routes:[route],route_count:1,research_note:null}}

function directFields(card:SandboxContactCard){const phones:string[]=[],emails:string[]=[],urls:string[]=[];for(const route of Array.isArray(card.routes)?card.routes:[]){const type=safeText(route.channel_type,60).toLowerCase(),value=safeText(route.value,800);if(!value)continue;if(type==='phone'||type==='switchboard')phones.push(value);else if(type==='email'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))emails.push(value);else if(['url','website','supplier_portal','form'].includes(type)){const url=httpUrl(value);if(url)urls.push(url)}}const website=httpUrl(card.website_url);if(website)urls.push(website);return{phones:[...new Set(phones)],emails:[...new Set(emails)],urls:[...new Set(urls)],address:safeText(card.address,300)}}

function eligible(card:SandboxContactCard){const name=safeText(card.subject_name||card.organization_name,180),fields=directFields(card);if(!name)return false;if(fields.phones.length||fields.emails.length||fields.urls.length||fields.address)return true;if(card.resolution_status==='named_routing_contact'){const org=safeText(card.organization_name,180),title=safeText(card.role_label,180),routing=(card.routes||[]).find(route=>safeText(route.channel_type,60).toLowerCase()==='routing_instruction'&&safeText(route.value,800));return!!routing&&!!(org||title)}return false}

function buildVcard(card:SandboxContactCard){const fields=directFields(card),name=safeText(card.subject_name||card.organization_name,180)||'Scout contact',org=safeText(card.organization_name,180),lines=['BEGIN:VCARD','VERSION:3.0','FN:'+escapeVcard(name),'N:;;;;'];if(org)lines.push('ORG:'+escapeVcard(org));if(card.role_label)lines.push('TITLE:'+escapeVcard(card.role_label));for(const phone of fields.phones)lines.push('TEL;TYPE=WORK:'+escapeVcard(phone));for(const email of fields.emails)lines.push('EMAIL;TYPE=INTERNET,WORK:'+escapeVcard(email));for(const url of fields.urls)lines.push('URL:'+escapeVcard(url));if(fields.address)lines.push('ADR;TYPE=WORK:;;'+escapeVcard(fields.address)+';;;;');const notes:string[]=[];if(card.site_name&&card.site_name!==name)notes.push('Site: '+safeText(card.site_name,180));for(const route of card.routes||[]){if(safeText(route.channel_type,60).toLowerCase()==='routing_instruction'&&route.value)notes.push(safeText(route.value,800))}if(notes.length)lines.push('NOTE:'+escapeVcard(notes.slice(0,2).join(' | ')));lines.push('REV:'+new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'),'END:VCARD');return lines.join('\r\n')+'\r\n'}

export async function prepareVcardDownload(targets:SandboxMapTarget[],targetKey:string,routeKey:string|null,baseUrl:string,secret:string){const target=targets.find(item=>item.key===targetKey),baseCard=target?.contact_card;if(!target||!baseCard)return null;let card=baseCard;if(routeKey){const route=(baseCard.routes||[]).find(item=>item.key===routeKey);if(!route)return null;const person=personCardFromRoute(baseCard,route);if(!person)return null;card=person}if(!eligible(card))return null;const name=safeText(card.subject_name||card.organization_name,180)||'Scout contact',filename=filenameFor(name),content=buildVcard(card),token=await sealPayload({exp:Date.now()+VCARD_DOWNLOAD_TTL_MS,filename,content},secret),downloadUrl=baseUrl.replace(/\/$/,'')+'/functions/v1/scout-component-sandbox-mcp/contact-vcard?token='+encodeURIComponent(token);return{download_url:downloadUrl,file_name:filename}}

export async function handleVcardDownloadRequest(req:Request,secret:string){const url=new URL(req.url);if(req.method!=='GET'||!url.pathname.endsWith('/contact-vcard'))return null;const token=url.searchParams.get('token')||'',payload=await openPayload(token,secret);if(!payload)return new Response('Download expired or invalid.',{status:410,headers:{'cache-control':'no-store','content-type':'text/plain; charset=utf-8','x-content-type-options':'nosniff','referrer-policy':'no-referrer'}});const ascii=payload.filename.replace(/[^A-Za-z0-9._-]/g,'-').slice(0,120)||'scout-contact.vcf';return new Response(payload.content,{status:200,headers:{'cache-control':'no-store, max-age=0','content-type':'text/vcard; charset=utf-8','content-disposition':`attachment; filename="${ascii}"; filename*=UTF-8''${encodeURIComponent(payload.filename)}`,'x-content-type-options':'nosniff','referrer-policy':'no-referrer','content-security-policy':"default-src 'none'; sandbox"}})}
