export const SCOUT_SPINE_SINGLE_ASSET_TYPES=[
 'bridge','construction_site','event_detailing','dam','mine_quarry','landfill','rail_crossing','roof_lifecycle','solar_lifecycle',
]as const
export type ScoutSpineSingleAssetType=typeof SCOUT_SPINE_SINGLE_ASSET_TYPES[number]
export const SCOUT_SPINE_SINGLE_ASSET_CONFIG={
 bridge:{label:'bridge condition / planned work',sourceKind:'bridge',signalKinds:['bridge_condition_or_inspection'],displayName:'I-64 EB',center:{lon:-84.851506,lat:38.161003},zoom:16,statusLabel:'Bridge condition signal',factLabels:['Structure','Condition','Inspection','Owner','Planned work'],guardrail:'Bridge condition, inspection cadence, and separately documented planned-work evidence support qualification only. Scout is not making a structural-engineering determination. A plan signal is not proof that work is funded, currently procuring, accessible, or available to a drone operator.'},
 construction_site:{label:'construction lifecycle',sourceKind:'construction_window',signalKinds:['construction_lifecycle'],displayName:'Commercial Alteration — 700 CENTRAL AVE',center:{lon:-85.77176682,lat:38.20415465},zoom:16,statusLabel:'Construction lifecycle signal',factLabels:['Address','Project type','Stage','Project value','Project area','Contractor'],guardrail:'The permit record supports a newly permitted construction-lifecycle signal. Stage is inferred from permit status and timing, not observed field progress. This does not prove a drone scope, active procurement, site access, buyer intent, or work availability.'},
 event_detailing:{label:'event-timed detailing',sourceKind:'event_detailing',signalKinds:['marquee_event_pre_detailing'],displayName:'2600 S FLOYD STREET',center:{lon:-85.7582934172167,lat:38.2083681570736},zoom:17,statusLabel:'Event-timed detailing signal',factLabels:['Event','Event date','Venue proximity','Timing basis','Independent need','Attendance context'],guardrail:'Independent exterior-cleaning evidence exists separately for this building. The marquee event may amplify timing only; event presence does not establish cleaning need. Attendance is a venue-capacity proxy, not an attendance forecast. This does not prove visible staining, procurement intent, site access, service authorization, or work availability.'},
 dam:{label:'dam condition / inspection cadence',sourceKind:'dam_condition_cadence',signalKinds:['dam_condition','dam_inspection_due'],displayName:'Hurricane Lake Dam',center:{lon:-85.64083333,lat:37.83305556},zoom:16,statusLabel:'Dam condition signal',factLabels:['Condition','Last inspection','Hazard potential','Inspection cadence','Regulator'],guardrail:'Authoritative condition and inspection-cadence records support investigation only. Scout is not making a dam-safety determination, declaring an inspection legally due, or asserting procurement, access, owner intent, or work availability.'},
 mine_quarry:{label:'mine / quarry material activity',sourceKind:'active_mine',signalKinds:['mine_material_activity'],displayName:'Calcar Quarry',center:{lon:-86.441389,lat:38.544167},zoom:16,statusLabel:'Active mine / quarry signal',factLabels:['Mine type','Status','Commodity','Operator'],guardrail:'Current operating status and commodity context support inspection, mapping, or volumetric qualification. They do not prove a measurement request, recurring service cadence, procurement, safe site access, or authorization to enter or operate at the mine.'},
 landfill:{label:'landfill capacity / gas context',sourceKind:'landfill',signalKinds:['landfill_capacity_gas'],displayName:'Nelson County SWDF',center:{lon:-85.5392,lat:37.8169},zoom:16,statusLabel:'Landfill capacity / gas signal',factLabels:['Status','Waste in place','Closure year','Owner','Gas collection'],guardrail:'Landfill capacity, closure, and gas-system context support investigation only. They do not establish a current inspection need, methane-service need, procurement, buyer intent, site access, or authorization to operate.'},
 rail_crossing:{label:'rail crossing context',sourceKind:'rail_crossing_context',signalKinds:['rail_crossing_risk'],displayName:'WALLER AVENUE / Norfolk Southern Railway Company / 724527H',center:{lon:-84.5160608,lat:38.0293018},zoom:16,statusLabel:'Rail crossing context signal',factLabels:['Crossing','Street','Railroad','Road traffic','Train movements','Timetable speed'],guardrail:'FRA crossing characteristics support account and inspection research; they are not a real-time incident alert or proof of maintenance need. The point does not define railroad property, right-of-way, safe operating airspace, access permission, or authorization to work near rail operations.'},
 roof_lifecycle:{label:'roof lifecycle',sourceKind:'roof_lifecycle',signalKinds:['roof_lifecycle'],displayName:'831 e broadway',center:{lon:-85.7379090168,lat:38.2449462311},zoom:17,statusLabel:'Roof lifecycle signal',factLabels:['Lifecycle band','Approx. age','Age anchor','Date precision','Replacement history'],guardrail:'The permit issue date is only an approximate original-building/roof age anchor. Scout does not know whether the roof was replaced later and is not asserting current roof condition, replacement need, procurement, buyer intent, access, or work availability.'},
 solar_lifecycle:{label:'solar lifecycle',sourceKind:'solar_lifecycle',signalKinds:['solar_lifecycle'],displayName:'Cooperative Solar Two-Fayette',center:{lon:-84.31579,lat:38.035403},zoom:15,statusLabel:'Solar lifecycle signal',factLabels:['Plant','Capacity','Lifecycle','Status code','Planned operation','Entity'],guardrail:'EIA lifecycle timing supports O&M and inspection qualification. It does not establish a defect, commissioning task, cleaning need, procurement, site access, interconnection status beyond the cited record, or work availability.'},
}as const satisfies Record<ScoutSpineSingleAssetType,{label:string;sourceKind:string;signalKinds:readonly string[];displayName:string;center:{lon:number;lat:number};zoom:number;statusLabel:string;factLabels:readonly string[];guardrail:string}>
export function isScoutSpineSingleAssetType(value:unknown):value is ScoutSpineSingleAssetType{return typeof value==='string'&&(SCOUT_SPINE_SINGLE_ASSET_TYPES as readonly string[]).includes(value)}
