import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2.57.4'

const SLUG='collect-buyer-document-evidence'
const db=createClient(Deno.env.get('SUPABASE_URL')!,serviceKey(),{auth:{persistSession:false,autoRefreshToken:false}})
const SEARCH='https://api.tavily.com/search'
const BLOCKED=['facebook.com','linkedin.com','instagram.com','x.com','twitter.com','yelp.com','bbb.org','mapquest.com','buildzoom.com','manta.com','chamberofcommerce.com','yellowpages.com','wikipedia.org','crunchbase.com','bloomberg.com','dnb.com','zoominfo.com','opencorporates.com','bizapedia.com']
const GENERIC_EMAIL=/^(info|contact|office|sales|estimating|estimate|bids?|bidroom|procurement|purchasing|vendor|vendors|supplier|facilities|maintenance|service|support|admin|hello)$/i
const ROUTE_PATH=/(contact|procure|purchas|vendor|supplier|subcontract|bid|estimating|registration|register)/i
const BRAND_STOP=new Set(['the','and','inc','incorporated','llc','ltd','corp','corporation','company','co','group','services','service','holdings','enterprises','usa','us','global','construction','contracting','contractors','engineering','electric','electrical','mechanical','heating','cooling','hvac','solar','energy','power','coop','cooperative','builders','building','roofing','plumbing'])

type O=Record<string,any>
type Job={id:string;organization_name:string;search_query?:string|null;source_roots?:unknown;context?:O}
type Route={contact_scope:string;channel_type:'phone'|'email'|'url';contact_value:string;stability_class:'institutional'|'departmental';confidence:number;label:string}
type Page={url:string;title:string;text:string;routes:Route[];follow:string[]}

function serviceKey(){try{const k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default;if(k)return k}catch{}const k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!k)throw new Error('Scout database credentials unavailable');return k}
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
function err(v:unknown){return String(v instanceof Error?v.message:v).replace(/Bearer\s+[\w.-]+/gi,'Bearer [REDACTED]').replace(/tvly-[\w-]+/g,'[REDACTED]').replace(/sb_secret_[\w-]+/g,'[REDACTED]').slice(0,1000)}
function norm(v:string){return String(v||'').toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]+/g,'')}
function domain(u:string){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,'')}catch{return''}}
function roots(v:unknown){return Array.isArray(v)?[...new Set(v.map(String).filter(x=>/^https?:\/\//i.test(x)))].slice(0,8):[]}
function plain(html:string){return html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function title(html:string){const m=html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);return m?plain(m[1]).slice(0,300):''}
function exactMentions(source:string,name:string){const x=norm(name);return x.length>=4&&norm(source.slice(0,40000)).includes(x)}
function brandTokens(name:string){const raw=name.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean).filter(x=>!BRAND_STOP.has(x));const long=raw.filter(x=>x.length>=4);if(long.length)return long.slice(0,3);return raw.length===1&&raw[0].length>=3?raw:[]}
function domainFits(u:string,name:string){const d=domain(u).replace(/[^a-z0-9]/g,'');const t=brandTokens(name);return t.length>0&&t.some(x=>d.includes(x))}
function brandMatches(source:string,name:string){const s=norm(source.slice(0,40000)),t=brandTokens(name);return t.length>0&&t.every(x=>s.includes(x))}
function scope(s:string){s=s.toLowerCase();if(/(supplier|vendor|subcontract|registration|register)/.test(s))return'supplier_registration';if(/(procure|purchas|bid|estimating)/.test(s))return'procurement';return'other'}
function dedupe(rs:Route[]){const m=new Map<string,Route>();for(const r of rs)m.set(`${r.contact_scope}|${r.channel_type}|${r.contact_value}`,r);return[...m.values()].slice(0,8)}
function governmentLike(name:string){return /(city|county|municipal|government|public works|department|authority|district|university|college|school|town|village|state of|commonwealth|federal)/i.test(name)}
function usableRoutes(p:Page,name:string){if(domain(p.url).endsWith('.gov')&&!governmentLike(name))return[];return p.routes}

function extract(base:string,html:string,text:string){const rs:Route[]=[];const follow:string[]=[];const d=domain(base);for(const m of html.matchAll(/href\s*=\s*["']([^"']+)["']/gi)){let u='';try{u=new URL(m[1],base).toString()}catch{continue};if(domain(u)!==d||!ROUTE_PATH.test(u))continue;follow.push(u);rs.push({contact_scope:scope(u),channel_type:'url',contact_value:u,stability_class:'institutional',confidence:.82,label:'Published organization route'})}for(const m of text.matchAll(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)){const email=m[0].toLowerCase();if(!GENERIC_EMAIL.test(email.split('@')[0]))continue;const around=text.slice(Math.max(0,(m.index||0)-100),(m.index||0)+email.length+100);rs.push({contact_scope:scope(around),channel_type:'email',contact_value:email,stability_class:scope(around)==='procurement'?'departmental':'institutional',confidence:.84,label:'Published generic organization email'})}for(const m of text.matchAll(/(?:\+?1[ .-]?)?\(?\d{3}\)?[ .-]\d{3}[ .-]\d{4}/g)){const v=m[0].trim(),around=text.slice(Math.max(0,(m.index||0)-80),(m.index||0)+v.length+80);if(/fax/i.test(around)||!/(phone|tel|call|office|contact|main|direct line|noc)/i.test(around))continue;rs.push({contact_scope:'general_switchboard',channel_type:'phone',contact_value:v,stability_class:'institutional',confidence:.82,label:'Published main/public phone'})}return{routes:dedupe(rs),follow:[...new Set(follow)].slice(0,4)}}

async function page(u:string):Promise<Page>{if(/\.(pdf|docx?|xlsx?)(\?|$)/i.test(u))throw new Error('non-html source');const r=await fetch(u,{redirect:'follow',signal:AbortSignal.timeout(10000),headers:{accept:'text/html,text/plain;q=0.9,*/*;q=0.5','user-agent':'Scout-by-Cadastory/1.0 buyer-evidence'}});if(!r.ok)throw new Error(`source HTTP ${r.status}`);const html=(await r.text()).slice(0,1500000),text=plain(html),ex=extract(r.url||u,html,text);return{url:r.url||u,title:title(html),text,routes:ex.routes,follow:ex.follow}}
async function inspect(seed:string,name:string,mode:'none'|'brand'|'exact'){let p:Page;try{p=await page(seed)}catch{return null};const matches=(q:Page)=>mode==='none'||(mode==='brand'?brandMatches(`${q.title}\n${q.text}`,name):exactMentions(`${q.title}\n${q.text}`,name));if(matches(p)&&usableRoutes(p,name).length)return p;for(const u of p.follow.slice(0,3)){try{const q=await page(u);if(!matches(q))continue;if(usableRoutes(q,name).length)return q;p=q}catch{}}return matches(p)?p:null}
async function search(job:Job,key:string|null,providerMode:string,identityMode:'brand'|'exact'){const headers:Record<string,string>={'content-type':'application/json'};if(key)headers.authorization=`Bearer ${key}`;else if(providerMode==='keyless')headers['x-tavily-access-mode']='keyless';else throw new Error('search provider unavailable');const r=await fetch(SEARCH,{method:'POST',signal:AbortSignal.timeout(12000),headers,body:JSON.stringify({query:job.search_query||`"${job.organization_name}" official website contact procurement vendor`,topic:'general',search_depth:'basic',max_results:5,include_answer:false,include_raw_content:false,include_images:false})});const raw=await r.text();if(!r.ok)throw new Error(`search provider HTTP ${r.status}: ${raw.slice(0,250)}`);const b=JSON.parse(raw);for(const x of Array.isArray(b?.results)?b.results:[]){const u=String(x?.url||''),d=domain(u),score=Number(x?.score??0);if(!u||/\.(pdf|docx?|xlsx?)(\?|$)/i.test(u)||d.endsWith('.gov')||BLOCKED.some(z=>d===z||d.endsWith(`.${z}`))||score<(identityMode==='brand'?.40:.45)||!domainFits(u,job.organization_name))continue;const p=await inspect(u,job.organization_name,identityMode);if(!p||!domainFits(p.url,job.organization_name))continue;return p}return null}
async function hash(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function complete(id:string,outcome:string,findings:O[],message:string|null=null){const r=await db.rpc('internal_complete_buyer_document_evidence_job',{p_job_id:id,p_outcome:outcome,p_findings:findings,p_error:message});if(r.error)throw new Error(`completion: ${r.error.message}`);return r.data}

async function materialize(job:Job){const r=await db.rpc('internal_materialize_authoritative_named_buyer_org_v1',{p_job_id:job.id});if(r.error)throw new Error(`identity materialization: ${r.error.message}`);return r.data||{}}
async function existingWebsite(orgId:string){const r=await db.schema('core').from('organizations').select('website_url').eq('id',orgId).maybeSingle();return !r.error&&r.data?.website_url?String(r.data.website_url):null}

async function process(job:Job,key:string|null,providerMode:string){
  const name=String(job.organization_name||'').trim();if(!name)return complete(job.id,'needs_review',[],'named organization required')
  let orgId=String(job.context?.organization_id||'')||null;let identity:O|null=null;let jobRoots=roots(job.source_roots)
  if(!orgId){identity=await materialize(job);if(identity?.status==='ambiguous_existing_organization')return complete(job.id,'needs_review',[],'multiple existing organizations match authoritative named buyer');orgId=String(identity?.organization_id||'')||null}
  if(orgId){const w=await existingWebsite(orgId);if(w&&!jobRoots.includes(w))jobRoots.unshift(w)}

  let p:Page|null=null,method='source_root'
  for(const u of jobRoots){p=await inspect(u,name,'none');if(p&&usableRoutes(p,name).length)break}
  if((!p||!usableRoutes(p,name).length)&&providerMode!=='disabled'){const q=await search(job,key,providerMode,orgId?'brand':'exact');if(q){p=q;method='search'}}
  if(!p)return complete(job.id,'no_evidence',[],providerMode!=='disabled'?'no supported first-party organization source found':'no supported evidence in documented source roots')

  const excerpt=`${p.title}\n${p.text}`.slice(0,3500);let resolution:O|null=null
  if(!orgId){const phone=usableRoutes(p,name).find(x=>x.channel_type==='phone')?.contact_value||null,website=`${new URL(p.url).origin}/`;const r=await db.rpc('internal_resolve_or_create_buyer_research_organization_v1',{p_job_id:job.id,p_canonical_name:name,p_website_url:website,p_phone:phone,p_source_url:p.url,p_source_authority:'First-party organization website (automated exact-name verification)',p_identity_confidence:.96,p_evidence_excerpt:excerpt});if(r.error)return complete(job.id,'needs_review',[],`organization identity requires review: ${r.error.message}`);resolution=r.data;if(r.data?.status==='ambiguous_existing_organization')return complete(job.id,'needs_review',[],'multiple existing organizations match researched buyer');orgId=String(r.data?.organization_id||'')||null;if(!orgId)return complete(job.id,'needs_review',[],'organization identity could not be made durable')}

  const routes=usableRoutes(p,name),ic=method==='source_root'?.97:.96
  const finding={fingerprint:await hash(`${p.url}|${name}|${JSON.stringify(routes)}`),source_url:p.url,source_authority:method==='source_root'?'Documented organization source root':'First-party organization website matched to authoritative organization identity',source_kind:'public_web_page',document_title:p.title||null,evidence_excerpt:excerpt,evidence_codes:routes.length?['buyer_identity_documented','public_contact_route']:['buyer_identity_documented'],extracted_values:{organization_name:name,organization_id:orgId,website_url:`${new URL(p.url).origin}/`,contact_routes:routes,discovery_method:method,buyer_authority_not_implied:true,identity_materialization:identity?.status||null},confidence:routes.length?.91:.88,identity_confidence:ic,decision_state:'documented',observed_at:new Date().toISOString(),auto_apply:routes.length>0}
  const outcome=routes.length?'completed':'no_evidence';const result=await complete(job.id,outcome,[finding],routes.length?null:'organization documented but no supported public route found');return{...result,identity_materialization:identity,organization_resolution:resolution,discovery_method:method,routes_found:routes.length}
}

async function authorized(req:Request){const k=req.headers.get('x-scout-key')||'';if(!k)return false;const r=await db.rpc('internal_validate_collector_key',{p_key:k});return!r.error&&r.data===true}
async function begin(limit:number){const r=await db.rpc('internal_begin_collector_run',{p_slug:SLUG,p_request_summary:{limit}});if(r.error||!r.data)throw new Error('collector run could not be recorded');return String(r.data)}
async function finish(id:string,status:'succeeded'|'failed'|'no_work',http:number,summary:O){const r=await db.rpc('internal_finish_collector_run',{p_run_id:id,p_status:status,p_http_status:http,p_summary:summary});if(r.error)throw new Error('collector result could not be recorded')}

Deno.serve(async req=>{if(req.method!=='POST')return response({error:'POST required'},405);if(!await authorized(req))return response({error:'unauthorized'},401);const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>32768)return response({error:'request_too_large'},413);let body:O={};try{body=JSON.parse(raw||'{}')}catch{return response({error:'invalid_json'},400)}const limit=Math.max(1,Math.min(6,Number(body.limit)||4));let run='';try{run=await begin(limit);const pc=await db.rpc('internal_get_buyer_research_provider_v1');if(pc.error)throw new Error(`provider config: ${pc.error.message}`);const providerMode=String(pc.data?.mode||((pc.data?.configured===true&&typeof pc.data?.api_key==='string')?'api_key':'disabled'));const key=typeof pc.data?.api_key==='string'&&pc.data.api_key?String(pc.data.api_key):null;const available=pc.data?.search_available===true||providerMode==='api_key'||providerMode==='keyless';const c=await db.rpc('internal_claim_buyer_web_research_jobs_v1',{p_limit:limit,p_search_available:available});if(c.error)throw new Error(`claim: ${c.error.message}`);const jobs:Job[]=Array.isArray(c.data)?c.data:[];const provider=providerMode==='keyless'?'tavily_keyless':providerMode==='api_key'?'tavily':'source_roots_only';if(!jobs.length){const s={outcome:'no_work',counts:{attempted:0,succeeded:0,failed:0},provider};await finish(run,'no_work',200,s);return response({ok:true,outcome:'no_work',run_id:run,claimed:0,processed:[],provider})}const processed:O[]=[];for(const job of jobs){try{processed.push({job_id:job.id,organization_name:job.organization_name,status:'succeeded',result:await process(job,key,providerMode)})}catch(e){const m=err(e);try{processed.push({job_id:job.id,organization_name:job.organization_name,status:'succeeded',result:await complete(job.id,'failed',[],m),worker_error:m})}catch(e2){throw new Error(`${m}; failure completion also failed: ${err(e2)}`)}}}const s={outcome:'succeeded',counts:{attempted:jobs.length,succeeded:processed.length,failed:0},provider,search_available:available};await finish(run,'succeeded',200,s);return response({ok:true,outcome:'succeeded',run_id:run,claimed:jobs.length,processed,provider,search_available:available})}catch(e){const m=err(e);if(run)try{await finish(run,'failed',500,{outcome:'failed',counts:{attempted:null,succeeded:null,failed:1},errors:[m]})}catch{};console.error(m);return response({ok:false,outcome:'failed',run_id:run||null,error:m},500)}})
