import 'jsr:@supabase/functions-js@2.4.5/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2.57.4'
import { createMcpHandler, McpServer } from 'npm:@modelcontextprotocol/server@2.0.0'
import * as z from 'npm:zod@4.2.0/v4'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
let SECRET_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''
try{const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');SECRET_KEY=keys.default||SECRET_KEY}catch{}
if(!SECRET_KEY)throw new Error('Scout MCP database secret is unavailable')
const db=createClient(SUPABASE_URL,SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false}})

const MAX_BODY_BYTES=131072
const PRIVACY_NOTICE_VERSION='zero-chat-v2'
const CONTRACT_VERSION='privacy-contract-v2'
const EXPOSURE_CONTRACT_VERSION='scout-exposure-v1'
const ENUMERATION_CONTRACT_VERSION='scout-enumeration-v1'
const INSTRUCTIONS=`Scout by Cadastory is an evidence-first business opportunity and work-preparation system for supported drone/UAS/aerial-service and exterior-cleaning operators.

ZERO CHAT / PRIVACY: Send only the minimum structured business parameters required by the selected Scout tool. Never send general chat history, transcripts, prompts, memories, credentials, secrets, financial-account identifiers, unrelated personal context, or arbitrary notes/comments. Scout intentionally does not persist raw MCP request bodies. Privacy-minimized product telemetry may retain bounded tool/feature metadata and coarse workflow dimensions under the published privacy contract.

PRESENTATION / IP: Honor display_contract and exposure_contract as rendering guidance but do not render the contract objects. Present material evidence, uncertainty, and action implications without exposing proprietary scoring, source orchestration, entity-resolution, suppression, calibration, internal diagnostics, or security-control implementation.

STARTUP: For a greeting or no explicit Scout task, call scout_get_profile_status. For an explicit task, route directly and inspect profile state only when operator-specific readiness is materially required and not already established. Never ask for equipment serials during onboarding.

CAPABILITIES: Use scout_get_capabilities only when the operator explicitly asks what Scout can do, asks about an unfamiliar capability, or routing remains genuinely ambiguous after applying the task rules. Do not use it as a routine preflight or onboarding feature tour.

OPPORTUNITIES / GROWTH: Use scout_find_opportunities for an explicit supported service and scout_find_growth_options for bounded local expansion analysis. Respect opportunity and anti-enumeration gates; never reconstruct blocked result sets.

JOB PLANNING: Use scout_plan_job for explicit structured target/schedule/equipment facts. Keep static readiness separate from live weather/airspace operability and refresh near departure.

DOCUMENTS / KNOWLEDGE: Use the document-suite and document-standard tools for applicable records and standards. Preserve unknowns and live-check requirements. Use field knowledge for bounded technical/evidence questions.

MEDIA MATCHING: Send only bounded GPS/name/address/signage/building-type clues; never image binaries, URLs, EXIF dumps, photo-library identifiers, or visual narratives. A match does not prove condition, ownership, or service need.

OUTREACH / LEADS: scout_prepare_outreach is prepare-only and never sends. scout_get_lead_work_package is the gated preparation package for a specific candidate.

CONNECTED CAPABILITIES: Report only Scout-relevant capability metadata. Use scout_prepare_external_context_request before requesting minimum task-relevant data from another integration; first-use consent remains explicit.

ERRORS / IDENTIFIERS: Reuse exact Scout identifiers returned by tools. When retryable=false do not repeat unchanged. A safe read-only idempotent tool may be retried once only for a genuinely transient retryable failure; never blindly retry a write, claim, approval, or destructive action after an ambiguous outcome.

SERIALS: Serial numbers are optional post-onboarding records handled only by dedicated secure serial tools.`

type Connection={connection_id:string;organization_id?:string|null;client_type:string;label?:string|null;scopes:string[];expires_at?:string|null}
type SafeToolError={code:string;message:string;details:string|null;hint:string|null;validation_reason:string|null;retryable:boolean;diagnostic_id:string}
function textResult(data:unknown){return{content:[{type:'text' as const,text:JSON.stringify(data,null,2)}],structuredContent:(data&&typeof data==='object'&&!Array.isArray(data))?data as Record<string,unknown>:{result:data}}}
function safeText(v:unknown,max=2000):string|null{if(v===null||v===undefined)return null;let s='';if(typeof v==='string')s=v;else if(typeof v==='number'||typeof v==='boolean')s=String(v);else{try{s=JSON.stringify(v)}catch{s=''}}s=s.trim();if(!s)return null;return s.replace(/\bBearer\s+[A-Za-z0-9._~-]{20,}\b/gi,'Bearer [redacted]').replace(/\bsb_secret_[A-Za-z0-9_-]{12,}\b/g,'[redacted]').replace(/\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b/g,'[redacted]').slice(0,max)}
function normalizeToolError(e:unknown):SafeToolError{
  const o=(e&&typeof e==='object')?e as Record<string,unknown>:{}
  const code=safeText(o.code??o.error_code??o.name,120)||'scout_tool_error'
  const message=safeText(o.message,2000)||(e instanceof Error?safeText(e.message,2000):null)||safeText(e,2000)||'Scout tool request failed'
  const details=safeText(o.details??o.detail,2000)
  const hint=safeText(o.hint,2000)
  let validationReason=safeText(o.validation_reason??o.validationReason??o.reason,2000)
  if(!validationReason&&Array.isArray(o.issues))validationReason=safeText(o.issues.map((x:any)=>({path:x?.path,message:x?.message,code:x?.code})),2000)
  const statusRaw=o.status??o.statusCode;const status=typeof statusRaw==='number'?statusRaw:Number(statusRaw)
  const explicit=o.retryable
  const retryable=typeof explicit==='boolean'?explicit:(status===408||status===429||status>=500||['40001','40P01','55P03','57014','57P01','08000','08003','08006'].includes(code))
  return{code,message,details,hint,validation_reason:validationReason,retryable,diagnostic_id:crypto.randomUUID()}
}
function errorResult(e:unknown){const error=normalizeToolError(e);const payload={error};return{isError:true,content:[{type:'text' as const,text:JSON.stringify(payload,null,2)}],structuredContent:payload}}
function getConnection(ctx:any):Connection{const c=ctx?.authInfo?.extra?.connection as Connection|undefined;if(!c?.connection_id)throw new Error('authenticated Scout connection context missing');return c}
function requireScope(c:Connection,scope:string){if(!Array.isArray(c.scopes)||!c.scopes.includes(scope))throw new Error(`connection does not grant ${scope}`)}
async function callRpc(name:string,args:Record<string,unknown>){const {data,error}=await db.rpc(name,args);if(error)throw error;return data}

const machineKey=z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/)
const shortMachineKey=z.string().regex(/^[a-z][a-z0-9_.-]{0,119}$/)
const technicalJson:z.ZodTypeAny=z.lazy(()=>z.union([z.string().max(500),z.number(),z.boolean(),z.null(),z.array(technicalJson).max(100),z.record(machineKey,technicalJson)]))
const httpUrl=z.string().max(2000).regex(/^https?:\/\//i)
const timestampText=z.string().max(80)
const equipmentItem=z.object({model_id:z.string().uuid().optional(),name:z.string().min(1).max(160).optional(),quantity:z.number().int().min(1).max(100).optional()}).strict()
const credentialItem=z.object({slug:shortMachineKey,state:z.enum(['active','expired','pursuing','none','unknown']),expires_at:z.string().max(20).nullable().optional(),jurisdiction_code:z.string().regex(/^[A-Za-z]{2,8}$/).optional()}).strict()
const readinessItem=z.object({key:shortMachineKey,class:z.enum(['insurance','calibration','plan','training','documentation','business_requirement','other']),state:z.enum(['current','expired','pursuing','none','unknown','not_applicable']),expires_at:z.string().max(20).nullable().optional(),jurisdiction_code:z.string().regex(/^[A-Za-z]{2,8}$/).optional(),scope:z.record(machineKey,z.union([z.string().max(300),z.number(),z.boolean(),z.null()])).optional()}).strict()
const rigCapability=z.object({slug:shortMachineKey,qualifier:z.string().max(120).optional(),value_boolean:z.boolean().optional(),value_numeric:z.number().optional(),value_text:z.string().max(300).optional(),value_json:technicalJson.optional(),unit:z.string().max(40).optional()}).strict()
const rigEquipmentItem=z.object({provider_equipment_id:z.string().uuid().optional(),model_id:z.string().uuid().optional(),name:z.string().min(1).max(160).optional(),quantity:z.number().int().min(1).max(100).optional(),role:z.string().min(1).max(80).optional()}).strict()
const rigFluidRouteItem=z.object({fluid_route_id:z.string().uuid().optional(),name:z.string().min(2).max(160).optional(),route_kind:z.enum(['cleaning_delivery','window_wash','rinse','chemical_transfer','mixed_service','other']).optional(),route_role:shortMachineKey.optional(),service_slug:shortMachineKey.optional(),status:z.enum(['active','backup','planned','retired']).optional()}).strict().refine(v=>v.fluid_route_id!==undefined||v.name!==undefined,{message:'fluid route requires fluid_route_id or name'})
const rigProductItem=z.object({provider_product_id:z.string().uuid().optional(),product_id:z.string().uuid().optional(),name:z.string().min(1).max(200).optional(),manufacturer:z.string().min(1).max(200).optional(),product_kind:shortMachineKey.optional(),concentration_as_purchased_pct:z.number().min(0).max(100).optional(),default_mix:technicalJson.optional(),application_role:shortMachineKey.optional(),service_slug:shortMachineKey.optional(),fluid_route_id:z.string().uuid().optional(),fluid_route_name:z.string().min(2).max(160).optional(),service_mode:shortMachineKey.optional(),status:z.enum(['active','inactive','planned']).optional()}).strict().refine(v=>v.provider_product_id!==undefined||v.product_id!==undefined||v.name!==undefined,{message:'rig product requires provider_product_id, product_id, or name'})
const rigItem=z.object({rig_id:z.string().uuid().optional(),name:z.string().min(2).max(120),status:z.enum(['active','inactive','seasonal','planned']).optional(),delivery_method:shortMachineKey.optional(),services:z.array(shortMachineKey).max(100).optional(),equipment:z.array(rigEquipmentItem).max(60).optional(),capabilities:z.array(rigCapability).max(100).optional(),fluid_routes:z.array(rigFluidRouteItem).max(20).optional(),products:z.array(rigProductItem).max(60).optional()}).strict()
const profilePatch=z.object({business_name:z.string().min(1).max(200).optional(),dba_name:z.string().max(200).nullable().optional(),sector:z.string().min(2).max(200).optional(),home_base:z.string().min(2).max(200).optional(),operating_states:z.array(z.string().regex(/^[A-Za-z]{2}$/)).min(1).max(20).optional(),preferred_radius_miles:z.number().min(0).max(1000).nullable().optional(),max_travel_miles:z.number().min(0).max(1000).nullable().optional(),crew_size:z.number().int().min(1).max(10000).nullable().optional(),willing_to_subcontract:z.boolean().nullable().optional(),services:z.array(shortMachineKey).max(200).optional(),services_confirmed:z.boolean().optional(),equipment:z.array(equipmentItem).max(100).optional(),equipment_confirmed:z.boolean().optional(),credentials:z.array(credentialItem).max(100).optional(),credentials_confirmed:z.boolean().optional(),rigs:z.array(rigItem).min(1).max(25).optional(),rigs_confirmed:z.boolean().optional(),cleaning_products_confirmed:z.boolean().optional(),readiness:z.array(readinessItem).max(100).optional()}).strict()
const categoryBooleans=z.object({field_tip:z.boolean().optional(),scout_update:z.boolean().optional(),recordkeeping:z.boolean().optional(),profile_checkin:z.boolean().optional(),business_insight:z.boolean().optional(),maintenance_reminder:z.boolean().optional()}).strict()
const categoryWeights=z.object({field_tip:z.number().min(0).max(10).optional(),scout_update:z.number().min(0).max(10).optional(),recordkeeping:z.number().min(0).max(10).optional(),profile_checkin:z.number().min(0).max(10).optional(),business_insight:z.number().min(0).max(10).optional(),maintenance_reminder:z.number().min(0).max(10).optional()}).strict()
const entryPreferencePatch=z.object({enabled:z.boolean().optional(),min_items:z.number().int().min(1).max(5).optional(),max_items:z.number().int().min(1).max(5).optional(),cta_mode:z.enum(['minimal','balanced','proactive']).optional(),max_profile_checkins:z.number().int().min(0).max(5).optional(),profile_prompt_days:z.number().int().min(1).max(3650).optional(),seasonal_recheck_days:z.number().int().min(1).max(3650).optional(),categories:categoryBooleans.optional(),category_weights:categoryWeights.optional()}).strict()
const sourceDoc=z.object({url:httpUrl,title:z.string().min(1).max(500),document_type:z.enum(['manufacturer_manual','manufacturer_product_data','manufacturer_product_reference','service_manual','service_bulletin','sds','regulatory_guidance','standard','peer_reviewed_research','industry_guidance','field_report','forum_discussion','training_material','procurement_record','contract_document','other']).optional(),publisher:z.string().max(200).optional(),published_at:timestampText.optional(),authority_tier:z.enum(['regulatory','manufacturer','standard','peer_reviewed','industry','field','anecdotal','unreviewed']).optional()}).strict()
const resolutionSchema=z.object({manufacturer_name:z.string().max(200).optional(),model_name:z.string().min(1).max(200),category:shortMachineKey,variant:z.string().max(160).optional(),lifecycle_status:z.enum(['current','discontinued','legacy','unknown']).optional(),manufacturer_website:httpUrl.optional(),specifications:technicalJson.optional()}).strict()
const researchedCapability=z.object({source_index:z.number().int().min(0).max(99),slug:shortMachineKey,confidence:z.number().min(0.1).max(1).optional(),statement:z.string().max(2000).optional(),source_location:z.string().max(500).optional(),qualifier:z.string().max(120).optional(),value_boolean:z.boolean().optional(),value_numeric:z.number().optional(),value_text:z.string().max(500).optional(),value_json:technicalJson.optional(),unit:z.string().max(40).optional(),conditions:technicalJson.optional()}).strict()
const wettedMaterial=z.object({source_index:z.number().int().min(0).max(99),material_slug:shortMachineKey,confidence:z.number().min(0.1).max(1).optional(),statement:z.string().max(2000).optional(),source_location:z.string().max(500).optional(),component_role:z.string().max(120).optional(),manufacturer_verified:z.boolean().optional(),service_mode:z.string().max(120).optional()}).strict()
const wettedStatus=z.object({source_index:z.number().int().min(0).max(99),inventory_status:z.enum(['unknown','partial','complete']),confidence:z.number().min(0.1).max(1).optional(),statement:z.string().max(2000).optional(),source_location:z.string().max(500).optional()}).strict()
const chemistryRule=z.object({source_index:z.number().int().min(0).max(99),chemical_agent_slug:shortMachineKey.optional(),product_slug:shortMachineKey.optional(),disposition:z.enum(['supported','conditional','not_recommended','prohibited','insufficient_data']),confidence:z.number().min(0.1).max(1).optional(),statement:z.string().max(2000).optional(),source_location:z.string().max(500).optional(),rule_scope:z.string().max(160).optional(),requirements:technicalJson.optional(),rationale:z.string().max(2000).optional()}).strict()
const fluidPath=z.object({source_index:z.number().int().min(0).max(99),confidence:z.number().min(0.1).max(1).optional(),statement:z.string().max(2000).optional(),source_location:z.string().max(500).optional(),system_kind:z.enum(['softwash','pressure_wash','window_wash','rinse','chemical_transfer','mixed_service','other']).optional(),component_role:z.string().max(120).optional(),wetted_inventory_status:z.enum(['unknown','partial','complete']).optional(),manufacturer_verified:z.boolean().optional(),path_kind:z.enum(['chemical_concentrate','water','mixed_solution','rinse','high_pressure','return_bypass','other']).optional(),max_pressure_psi:z.number().min(0).optional(),max_flow_gpm:z.number().min(0).optional(),start_boundary:z.string().max(160).optional(),end_boundary:z.string().max(160).optional(),exposure_mode:z.enum(['full_stream','concentrate_only','water_only','mixed_solution','bypass_return','intermittent']).optional()}).strict()
const fieldClaim=z.object({source_index:z.number().int().min(0).max(99),claim_type:z.enum(['specification','operating_limit','maintenance','troubleshooting','compatibility','incompatibility','safety_absolute','engineering_principle','performance','business_practice','regulatory_requirement','other']),statement:z.string().min(1).max(3000),structured_value:technicalJson.optional(),source_location:z.string().max(500).optional(),applicability:technicalJson.optional(),hard_stop:z.boolean().optional(),confidence:z.number().min(0.1).max(1).optional()}).strict()
const compatibilityBundle=z.object({sources:z.array(sourceDoc).max(100).optional(),resolution:resolutionSchema.optional(),capabilities:z.array(researchedCapability).max(200).optional(),wetted_materials:z.array(wettedMaterial).max(200).optional(),wetted_status:wettedStatus.optional(),chemistry_rules:z.array(chemistryRule).max(200).optional(),fluid_path:fluidPath.optional(),field_claims:z.array(fieldClaim).max(300).optional(),unresolved_domains:z.array(shortMachineKey).max(100).optional()}).strict()
const recallSource=z.object({source_url:httpUrl,source_name:z.string().max(160).optional(),checked_at:timestampText.optional(),result_code:z.enum(['checked','unavailable','no_matching_notice','matching_notice_found']).optional()}).strict()
const serialScope=z.union([z.object({mode:z.literal('all_model')}).strict(),z.object({mode:z.literal('unknown')}).strict(),z.object({mode:z.literal('exact'),values:z.array(z.string().min(1).max(160)).max(500)}).strict(),z.object({mode:z.literal('prefix'),values:z.array(z.string().min(1).max(160)).max(500)}).strict(),z.object({mode:z.literal('range'),ranges:z.array(z.object({start:z.string().min(1).max(160),end:z.string().min(1).max(160)}).strict()).max(200)}).strict()])
const recallNotice=z.object({source_url:httpUrl,title:z.string().min(1).max(500),bulletin_type:z.enum(['recall','safety_notice','service_bulletin','firmware_safety','other']).optional(),status:z.enum(['active','resolved','superseded','unknown']).optional(),serial_scope:serialScope.optional(),summary:z.string().max(2000).optional(),source_name:z.string().max(160).optional(),published_at:timestampText.optional()}).strict()
const externalScope=z.object({target_name:z.string().max(200).optional(),target_location:z.string().max(300).optional(),project_reference:z.string().max(160).optional(),job_reference:z.string().max(160).optional(),asset_reference:z.string().max(160).optional(),contact_role:z.string().max(120).optional(),start_at:timestampText.optional(),end_at:timestampText.optional(),state_code:z.string().regex(/^[A-Za-z]{2}$/).optional(),radius_miles:z.number().min(0).max(1000).optional(),record_limit:z.number().int().min(1).max(100).optional()}).strict()
const purposeCode=z.enum(['schedule_availability','schedule_job','business_contact_lookup','opportunity_lookup','job_lookup','job_cost_context','fleet_inventory_lookup','maintenance_status_lookup','flight_history_lookup','telemetry_lookup','mapping_output_lookup','media_asset_lookup','project_lookup','project_location_lookup','mission_lookup','mission_create','weather_context_lookup','airspace_context_lookup','authorization_request'])
const fitFilter=z.enum(['ready','needs_verification','insufficient_profile','not_fully_modeled','blocked','pursuable'])
const proposalChannel=z.enum(['email','facebook_organic','facebook_paid','instagram_organic','instagram_paid','phone','sms','web_landing_page'])
const documentConditionFlags=z.object({controlled_airspace_requires_authorization:z.boolean().optional(),regulated_survey_deliverable:z.boolean().optional(),mine_site_entry_required:z.boolean().optional(),wildlife_recovery_legal_clearance_required:z.boolean().optional(),state_law_or_product_label_requires_applicator_credential:z.boolean().optional(),bulk_oil_storage_applicable:z.boolean().optional(),emergency_action_plan_required:z.boolean().optional()}).strict()
const documentContext=z.object({human_entry:z.boolean().optional(),respirator_required:z.boolean().optional(),fall_exposure:z.boolean().optional(),hazardous_energy:z.boolean().optional(),contract_framework:z.literal('usace').optional(),condition_flags:documentConditionFlags.optional()}).strict()
const scheduledTimestamp=z.string().min(10).max(80).refine(v=>Number.isFinite(Date.parse(v)),{message:'must be an ISO-compatible timestamp'})
const jobTarget=z.object({site_name:z.string().min(1).max(180).optional(),address:z.string().min(1).max(300).optional(),latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional(),state_code:z.string().regex(/^[A-Za-z]{2}$/).optional(),county_name:z.string().min(1).max(120).optional(),jurisdiction_code:z.string().regex(/^[A-Za-z0-9_-]{2,16}$/).optional()}).strict()
const jobEquipmentSelection=z.object({provider_equipment_id:z.string().uuid(),provider_equipment_unit_id:z.string().uuid().optional(),role:z.enum(['primary_platform','support_system','controller','payload','power','application_system','spare','other']).optional(),required:z.boolean().optional()}).strict()
const jobOperatingPlan=z.object({fluid_path_id:z.string().uuid().optional(),chemical_agent_id:z.string().uuid().optional(),product_id:z.string().uuid().optional(),pressure_psi:z.number().min(0).max(100000).optional(),flow_gpm:z.number().min(0).max(100000).optional(),temperature_f:z.number().min(-100).max(1000).optional(),weather_max_age_hours:z.number().min(0).max(168).optional(),airspace_max_age_minutes:z.number().min(0).max(1440).optional()}).strict()
const observedBuildingType=z.enum(['commercial','industrial','institutional','multifamily','retail','office','hospitality','education','healthcare','government','residential','unknown'])
const mediaMatchInput=z.object({latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional(),business_hint:z.string().min(1).max(180).optional(),address_hint:z.string().min(1).max(300).optional(),visible_text:z.string().min(1).max(160).optional(),observed_building_type:observedBuildingType.optional(),search_radius_m:z.number().int().min(10).max(10000).optional()}).strict().refine(v=>(v.latitude===undefined)===(v.longitude===undefined),{message:'latitude and longitude must be supplied together'}).refine(v=>v.latitude!==undefined||v.business_hint!==undefined||v.address_hint!==undefined||v.visible_text!==undefined,{message:'provide coordinates, a business hint, an address hint, or visible signage text'})
const growthOptionsInput=z.object({budget:z.number().min(0).max(100000000).optional(),county_name:z.string().min(1).max(120).optional(),state_code:z.string().regex(/^[A-Za-z]{2}$/).optional(),center_lat:z.number().min(-90).max(90).optional(),center_lon:z.number().min(-180).max(180).optional(),radius_miles:z.number().min(0.1).max(1000).optional(),jurisdiction_code:z.string().regex(/^[A-Za-z0-9_-]{2,16}$/).optional(),include_existing:z.boolean().optional(),limit:z.number().int().min(1).max(20).optional()}).strict().refine(v=>(v.county_name===undefined)===(v.state_code===undefined),{message:'county_name and state_code must be supplied together'}).refine(v=>{const n=[v.center_lat,v.center_lon,v.radius_miles].filter(x=>x!==undefined).length;return n===0||n===3},{message:'center_lat, center_lon, and radius_miles must be supplied together'}).refine(v=>v.county_name!==undefined||v.center_lat!==undefined,{message:'provide a county and state or a center point and radius'})
const cleaningCompatibilityInput=z.object({rig_id:z.string().uuid().optional(),provider_equipment_id:z.string().uuid().optional(),provider_product_id:z.string().uuid().optional(),limit:z.number().int().min(1).max(20).optional()}).strict()
const capabilityCategory=z.enum(['setup','equipment','opportunities','planning','documents','briefing','integrations','privacy'])

const forbiddenKeys=new Set(['conversation','conversations','messages','chat_history','chat_log','chatlog','transcript','transcripts','memory','memories','system_prompt','developer_prompt','password','passcode','secret','api_key','access_token','refresh_token','cookie','cookies','authorization_header','ssn','social_security_number','date_of_birth','dob','drivers_license','driver_license','passport','passport_number','bank_account','bank_account_number','routing_number','credit_card','card_number','cvv','cvc','medical_history','diagnosis','therapy_notes','religion','race','ethnicity','sexual_orientation','sex_life','political_affiliation','union_membership','criminal_history','notes','note','comments','comment','free_text','freetext'])
function normKey(k:string){return k.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
function looksLikeSecret(s:string){return /-----BEGIN [A-Z ]*PRIVATE KEY-----/.test(s)||/\bsb_secret_[A-Za-z0-9_-]{12,}\b/.test(s)||/\bsk-(?:proj-)?[A-Za-z0-9_-]{20,}\b/.test(s)||/\bgh[pousr]_[A-Za-z0-9]{20,}\b/.test(s)||/\bxox[baprs]-[A-Za-z0-9-]{10,}\b/.test(s)||/\bBearer\s+[A-Za-z0-9._~-]{20,}\b/i.test(s)||/\beyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b/.test(s)}
function looksLikeChatDump(s:string){if(s.length<1000)return false;const markers=s.match(/(?:^|\n)\s*(?:user|assistant|human|system|developer)\s*:/gim);return(markers?.length||0)>=3}
function inspectValue(v:unknown,tool:string,flags:Set<string>,depth=0,path:string[]=[]){if(depth>10){flags.add('payload_too_deep');return}if(typeof v==='string'){const last=path[path.length-1]||'';const serialException=tool==='scout_store_equipment_serial'&&normKey(last)==='serial_number';if(!serialException&&/^\d{3}-\d{2}-\d{4}$/.test(v.trim()))flags.add('ssn_like_value');if(looksLikeSecret(v))flags.add('secret_like_value');if(looksLikeChatDump(v))flags.add('chat_transcript_like_value');return}if(Array.isArray(v)){for(const x of v)inspectValue(x,tool,flags,depth+1,path);return}if(v&&typeof v==='object')for(const[k,x]of Object.entries(v as Record<string,unknown>)){const nk=normKey(k);const serialException=tool==='scout_store_equipment_serial'&&nk==='serial_number';if(!serialException&&forbiddenKeys.has(nk))flags.add(`forbidden_key:${nk}`);inspectValue(x,tool,flags,depth+1,[...path,k])}}
type Preflight={ok:boolean;status:number;toolName:string|null;argumentKeys:string[];flags:string[];requestId:string|null;reason?:string}
function preflight(raw:string,connection:Connection):Preflight{if(!raw)return{ok:true,status:200,toolName:null,argumentKeys:[],flags:[],requestId:null};let parsed:any;try{parsed=JSON.parse(raw)}catch{return{ok:false,status:400,toolName:null,argumentKeys:[],flags:['invalid_json'],requestId:null,reason:'invalid JSON-RPC payload'}};const items=Array.isArray(parsed)?parsed:[parsed];const flags=new Set<string>();const keys=new Set<string>();let toolName:string|null=null;let requestId:string|null=null;for(const item of items){if(!item||typeof item!=='object')continue;if(item.id!==undefined&&requestId===null)requestId=String(item.id).slice(0,160);if(item.method!=='tools/call')continue;const name=typeof item.params?.name==='string'?item.params.name:'';toolName=toolName?`${toolName},${name}`.slice(0,500):name;const args=(item.params?.arguments&&typeof item.params.arguments==='object'&&!Array.isArray(item.params.arguments))?item.params.arguments:{};Object.keys(args).forEach(k=>keys.add(k));inspectValue(args,name,flags)}if(flags.size)return{ok:false,status:422,toolName,argumentKeys:[...keys].sort(),flags:[...flags],requestId,reason:'Scout rejected fields that are outside the business-only privacy boundary'};return{ok:true,status:200,toolName,argumentKeys:[...keys].sort(),flags:[],requestId}}
async function readBodyLimited(req:Request,max:number){if(!req.body)return'';const reader=req.body.getReader();const chunks:Uint8Array[]=[];let total=0;try{while(true){const{done,value}=await reader.read();if(done)break;if(!value)continue;total+=value.byteLength;if(total>max)throw new Error('request_too_large');chunks.push(value)}}finally{reader.releaseLock()}const merged=new Uint8Array(total);let off=0;for(const c of chunks){merged.set(c,off);off+=c.byteLength}return new TextDecoder().decode(merged)}
async function audit(connection:Connection,pf:Preflight,outcome:string,requestBytes:number,durationMs:number,httpStatus:number){try{await db.rpc('scout_record_agent_request_event',{p_connection_id:connection.connection_id,p_tool_name:pf.toolName,p_protocol_method:'tools/call',p_outcome:outcome,p_request_bytes:requestBytes,p_argument_keys:pf.argumentKeys,p_privacy_flags:pf.flags,p_duration_ms:durationMs,p_http_status:httpStatus,p_request_id:pf.requestId})}catch{}}

const mcp=createMcpHandler((ctx)=>{
  const connection=getConnection(ctx)
  const server=new McpServer({name:'Scout by Cadastory',version:'1.5.1',description:'Evidence-first opportunity, growth, compatibility, operator-fit, document-suite, and work-package intelligence with zero-chat privacy, structured tool errors, proprietary-method, and anti-enumeration contracts.'},{instructions:INSTRUCTIONS})
  const present=async(toolName:string,data:unknown)=>await callRpc('scout_decorate_agent_response_v2',{p_connection_id:connection.connection_id,p_tool_name:toolName,p_payload:data??null})
  const wrap=(toolName:string,fn:()=>Promise<unknown>)=>fn().then(data=>present(toolName,data)).then(textResult).catch(errorResult)

  server.registerTool('scout_get_capabilities',{title:'Get Scout Capabilities',description:'Use when the operator explicitly asks what Scout can do or routing remains genuinely ambiguous. Do not use as a routine task or startup preflight.',inputSchema:z.object({query:z.string().min(1).max(200).optional(),category:capabilityCategory.optional(),include_services:z.boolean().optional(),include_external:z.boolean().optional()}).strict()},async({query,category,include_services,include_external})=>wrap('scout_get_capabilities',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_capability_manifest',{p_connection_id:connection.connection_id,p_query:query??null,p_category:category??null,p_include_services:include_services??false,p_include_external:include_external??true})}))
  server.registerTool('scout_get_profile_status',{title:'Get Scout Profile Status',description:'Use for a greeting/no explicit Scout task or when the requested work materially needs unknown operator readiness. Do not use as a universal preflight.',inputSchema:z.object({})},async()=>wrap('scout_get_profile_status',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_onboarding_status',{p_connection_id:connection.connection_id})}))
  server.registerTool('scout_update_profile',{title:'Update Scout Operator Profile',description:'Persist typed business setup, services, rigs, equipment, cleaning products/fluid routes, credentials, readiness, and progressive fields.',inputSchema:z.object({patch:profilePatch}).strict()},async({patch})=>wrap('scout_update_profile',async()=>{requireScope(connection,'profile:write');return callRpc('scout_update_connection_profile_v2',{p_connection_id:connection.connection_id,p_patch:patch})}))
  server.registerTool('scout_get_cleaning_compatibility',{title:'Get Cleaning Compatibility',description:'Read bounded static rig/equipment/product compatibility evidence.',inputSchema:cleaningCompatibilityInput},async(a)=>wrap('scout_get_cleaning_compatibility',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_cleaning_compatibility_v2',{p_connection_id:connection.connection_id,p_rig_id:a.rig_id??null,p_provider_equipment_id:a.provider_equipment_id??null,p_provider_product_id:a.provider_product_id??null,p_limit:a.limit??12})}))
  server.registerTool('scout_claim_compatibility_research_task',{title:'Claim Compatibility Research Task',description:'Claim one pending equipment/component compatibility research task. This changes task ownership/state; do not use for read-only compatibility questions.',inputSchema:z.object({limit:z.number().int().min(1).max(5).optional()}).strict()},async({limit})=>wrap('scout_claim_compatibility_research_task',async()=>{requireScope(connection,'profile:write');return callRpc('scout_claim_connection_compatibility_research',{p_connection_id:connection.connection_id,p_limit:limit??3})}))
  server.registerTool('scout_get_compatibility_research',{title:'Claim Compatibility Research Task (Legacy Alias)',description:'Legacy alias for scout_claim_compatibility_research_task. It remains callable for stale clients but is hidden from new model-facing catalogs.',inputSchema:z.object({limit:z.number().int().min(1).max(5).optional()}).strict()},async({limit})=>wrap('scout_get_compatibility_research',async()=>{requireScope(connection,'profile:write');return callRpc('scout_claim_connection_compatibility_research',{p_connection_id:connection.connection_id,p_limit:limit??3})}))
  server.registerTool('scout_submit_compatibility_research',{title:'Submit Compatibility Research',description:'Persist sourced technical evidence through a typed contract.',inputSchema:z.object({research_request_id:z.string().uuid(),bundle:compatibilityBundle}).strict()},async({research_request_id,bundle})=>wrap('scout_submit_compatibility_research',async()=>{requireScope(connection,'profile:write');return callRpc('scout_submit_connection_compatibility_research_v2',{p_connection_id:connection.connection_id,p_request_id:research_request_id,p_bundle:bundle})}))
  server.registerTool('scout_create_compatibility_override',{title:'Create 7-Day Compatibility Override',description:'Create a provisional visibility override only after unresolved research and explicit operator agreement.',inputSchema:z.object({research_request_id:z.string().uuid(),reason_code:z.enum(['research_exhausted','operator_accepts_uncertainty','field_verification_pending'])}).strict()},async({research_request_id,reason_code})=>wrap('scout_create_compatibility_override',async()=>{requireScope(connection,'profile:write');return callRpc('scout_create_connection_compatibility_override_v2',{p_connection_id:connection.connection_id,p_request_id:research_request_id,p_reason_code:reason_code})}))
  server.registerTool('scout_revoke_compatibility_override',{title:'Revoke Compatibility Override',description:'Revoke an active provisional compatibility override.',inputSchema:z.object({override_id:z.string().uuid(),reason_code:z.enum(['operator_revoked','compatibility_resolved','equipment_changed','risk_identified']).optional()}).strict()},async({override_id,reason_code})=>wrap('scout_revoke_compatibility_override',async()=>{requireScope(connection,'profile:write');return callRpc('scout_revoke_connection_compatibility_override_v2',{p_connection_id:connection.connection_id,p_override_id:override_id,p_reason_code:reason_code??'operator_revoked'})}))
  server.registerTool('scout_get_serial_recordkeeping_options',{title:'Get Secure Serial Recordkeeping Options',description:'Read confirmed units eligible for optional encrypted serial recordkeeping.',inputSchema:z.object({})},async()=>wrap('scout_get_serial_recordkeeping_options',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_serial_recordkeeping_options',{p_connection_id:connection.connection_id})}))
  server.registerTool('scout_store_equipment_serial',{title:'Store Equipment Serial Securely',description:'Store one operator-selected equipment serial through the encrypted recordkeeping path.',inputSchema:z.object({provider_equipment_id:z.string().uuid(),serial_number:z.string().min(3).max(160),recall_watch_enabled:z.boolean().optional(),unit_id:z.string().uuid().optional(),nickname:z.string().max(120).optional()}).strict()},async({provider_equipment_id,serial_number,recall_watch_enabled,unit_id,nickname})=>wrap('scout_store_equipment_serial',async()=>{requireScope(connection,'profile:write');return callRpc('scout_store_connection_equipment_serial',{p_connection_id:connection.connection_id,p_provider_equipment_id:provider_equipment_id,p_serial_number:serial_number,p_recall_watch_enabled:recall_watch_enabled??true,p_unit_id:unit_id??null,p_nickname:nickname??null})}))
  server.registerTool('scout_reveal_equipment_serial',{title:'Reveal Stored Equipment Serial',description:'Explicitly retrieve one stored serial.',inputSchema:z.object({record_id:z.string().uuid()}).strict()},async({record_id})=>wrap('scout_reveal_equipment_serial',async()=>{requireScope(connection,'profile:read');return callRpc('scout_reveal_connection_equipment_serial',{p_connection_id:connection.connection_id,p_record_id:record_id})}))
  server.registerTool('scout_delete_equipment_serial',{title:'Delete Stored Equipment Serial',description:'Delete one encrypted serial record.',inputSchema:z.object({record_id:z.string().uuid()}).strict()},async({record_id})=>wrap('scout_delete_equipment_serial',async()=>{requireScope(connection,'profile:write');return callRpc('scout_delete_connection_equipment_serial',{p_connection_id:connection.connection_id,p_record_id:record_id})}))
  server.registerTool('scout_update_recall_watch',{title:'Update Equipment Recall Watch',description:'Enable or disable recall watching for a stored unit.',inputSchema:z.object({record_id:z.string().uuid(),enabled:z.boolean(),interval_days:z.number().int().min(1).max(90).optional()}).strict()},async({record_id,enabled,interval_days})=>wrap('scout_update_recall_watch',async()=>{requireScope(connection,'profile:write');return callRpc('scout_update_connection_recall_watch',{p_connection_id:connection.connection_id,p_record_id:record_id,p_enabled:enabled,p_interval_days:interval_days??null})}))
  server.registerTool('scout_get_due_recall_checks',{title:'Get Due Recall Watch Checks',description:'Return due public recall research tasks without plaintext serials.',inputSchema:z.object({limit:z.number().int().min(1).max(20).optional()}).strict()},async({limit})=>wrap('scout_get_due_recall_checks',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_due_recall_checks',{p_connection_id:connection.connection_id,p_limit:limit??3})}))
  server.registerTool('scout_submit_recall_check',{title:'Submit Recall Watch Check',description:'Persist typed public recall research.',inputSchema:z.object({record_id:z.string().uuid(),checked_sources:z.array(recallSource).max(30),notices:z.array(recallNotice).max(50).optional()}).strict()},async({record_id,checked_sources,notices})=>wrap('scout_submit_recall_check',async()=>{requireScope(connection,'profile:write');return callRpc('scout_submit_connection_recall_check_v2',{p_connection_id:connection.connection_id,p_record_id:record_id,p_checked_sources:checked_sources,p_notices:notices??[]})}))
  server.registerTool('scout_check_opportunity_access',{title:'Check Scout Opportunity Access',description:'Check service prerequisites without revealing blocked opportunity sets.',inputSchema:z.object({service_slugs:z.array(shortMachineKey).min(1).max(50),state_code:z.string().regex(/^[A-Za-z]{2}$/).optional(),controlled_airspace_requires_authorization:z.boolean().optional(),condition_flags:z.record(machineKey,z.boolean()).optional()}).strict()},async({service_slugs,state_code,controlled_airspace_requires_authorization,condition_flags})=>wrap('scout_check_opportunity_access',async()=>{requireScope(connection,'profile:read');const p_context:Record<string,unknown>={};if(state_code)p_context.state_code=state_code.toUpperCase();if(controlled_airspace_requires_authorization!==undefined)p_context.controlled_airspace_requires_authorization=controlled_airspace_requires_authorization;if(condition_flags)p_context.condition_flags=condition_flags;return callRpc('scout_guard_opportunity_request',{p_connection_id:connection.connection_id,p_service_slugs:service_slugs,p_context})}))
  server.registerTool('scout_find_growth_options',{title:'Explore Scout Growth Options',description:'Compare evidence-backed local service-growth options with operator readiness and optional explicit aggregate budget.',inputSchema:growthOptionsInput},async(a)=>wrap('scout_find_growth_options',async()=>{requireScope(connection,'profile:read');requireScope(connection,'opportunities:read');return callRpc('scout_find_connection_growth_options_v2',{p_connection_id:connection.connection_id,p_budget:a.budget??null,p_county_name:a.county_name??null,p_state_code:a.state_code?.toUpperCase()??null,p_center_lat:a.center_lat??null,p_center_lon:a.center_lon??null,p_radius_miles:a.radius_miles??null,p_jurisdiction_code:a.jurisdiction_code?.toUpperCase()??null,p_include_existing:a.include_existing??false,p_limit:a.limit??10})}))
  server.registerTool('scout_find_opportunities',{title:'Find Scout Opportunities',description:'Find evidence-backed opportunities for one explicit service.',inputSchema:z.object({service_slug:shortMachineKey,county_name:z.string().max(120).optional(),state_code:z.string().regex(/^[A-Za-z]{2}$/).optional(),center_lat:z.number().min(-90).max(90).optional(),center_lon:z.number().min(-180).max(180).optional(),radius_miles:z.number().min(0.1).max(1000).optional(),jurisdiction_code:z.string().max(16).optional(),time_sensitive:z.boolean().optional(),require_contact:z.boolean().optional(),fit_filter:fitFilter.optional(),limit:z.number().int().min(1).max(25).optional()}).strict()},async(a)=>wrap('scout_find_opportunities',async()=>{requireScope(connection,'opportunities:read');requireScope(connection,'profile:read');return callRpc('scout_find_connection_opportunities_v2',{p_connection_id:connection.connection_id,p_service_slug:a.service_slug,p_county_name:a.county_name??null,p_state_code:a.state_code?.toUpperCase()??null,p_center_lat:a.center_lat??null,p_center_lon:a.center_lon??null,p_radius_miles:a.radius_miles??null,p_jurisdiction_code:a.jurisdiction_code?.toUpperCase()??null,p_time_sensitive:a.time_sensitive??false,p_require_contact:a.require_contact??false,p_fit_filter:a.fit_filter??null,p_limit:a.limit??10})}))
  server.registerTool('scout_get_discovery_status',{title:'Get Scout Discovery Status',description:'Return customer-safe discovery-control state.',inputSchema:z.object({})},async()=>wrap('scout_get_discovery_status',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_discovery_status',{p_connection_id:connection.connection_id})}))
  server.registerTool('scout_get_document_suite',{title:'Get Service Document Suite',description:'Build the operator-aware document bundle for explicit services.',inputSchema:z.object({service_slugs:z.array(shortMachineKey).min(1).max(20),jurisdiction:z.string().max(16).optional(),context:documentContext.optional()}).strict()},async({service_slugs,jurisdiction,context})=>wrap('scout_get_document_suite',async()=>{requireScope(connection,'knowledge:read');requireScope(connection,'profile:read');return callRpc('scout_get_connection_document_suite_v2',{p_connection_id:connection.connection_id,p_service_slugs:service_slugs,p_jurisdiction:jurisdiction?.toUpperCase()??null,p_context:context??{}})}))
  server.registerTool('scout_get_lead_work_package',{title:'Get Lead Work Package',description:'Build the gated opportunity, operator-fit, document, proposal, and compliance work package for one candidate.',inputSchema:z.object({candidate_key:z.string().min(3).max(300),jurisdiction_code:z.string().max(16).optional(),channel:proposalChannel.optional()}).strict()},async({candidate_key,jurisdiction_code,channel})=>wrap('scout_get_lead_work_package',async()=>{requireScope(connection,'opportunities:read');requireScope(connection,'knowledge:read');requireScope(connection,'profile:read');return callRpc('scout_get_connection_lead_work_package_v2',{p_connection_id:connection.connection_id,p_candidate_key:candidate_key,p_jurisdiction_code:jurisdiction_code?.toUpperCase()??null,p_channel:channel??'email'})}))
  server.registerTool('scout_match_media_asset',{title:'Match Building Photo to Business',description:'Match bounded GPS/business/address/signage/building-type clues without receiving image data.',inputSchema:mediaMatchInput},async(a)=>wrap('scout_match_media_asset',async()=>{requireScope(connection,'profile:read');requireScope(connection,'opportunities:read');return callRpc('scout_match_connection_media_asset_v2',{p_connection_id:connection.connection_id,p_latitude:a.latitude??null,p_longitude:a.longitude??null,p_business_hint:a.business_hint??null,p_address_hint:a.address_hint??null,p_visible_text:a.visible_text??null,p_observed_building_type:a.observed_building_type??null,p_search_radius_m:a.search_radius_m??500})}))
  server.registerTool('scout_prepare_outreach',{title:'Prepare Evidence-Backed Outreach',description:'Build a human-reviewed prepare-only outreach brief for one candidate.',inputSchema:z.object({candidate_key:z.string().min(3).max(300),jurisdiction_code:z.string().regex(/^[A-Za-z0-9_-]{2,16}$/).optional(),channel:proposalChannel.optional()}).strict()},async({candidate_key,jurisdiction_code,channel})=>wrap('scout_prepare_outreach',async()=>{requireScope(connection,'profile:read');requireScope(connection,'opportunities:read');requireScope(connection,'knowledge:read');return callRpc('scout_prepare_connection_outreach_v2',{p_connection_id:connection.connection_id,p_candidate_key:candidate_key,p_jurisdiction_code:jurisdiction_code?.toUpperCase()??null,p_channel:channel??'email'})}))
  server.registerTool('scout_plan_job',{title:'Plan a Scout Job',description:'Create a structured job, run static preflight, and optionally queue live checks.',inputSchema:z.object({service_slug:shortMachineKey,scheduled_start:scheduledTimestamp,scheduled_end:scheduledTimestamp.optional(),target:jobTarget,delivery_method_slug:shortMachineKey.optional(),equipment:z.array(jobEquipmentSelection).max(40).optional(),operating_plan:jobOperatingPlan.optional(),candidate_key:z.string().min(3).max(300).optional(),queue_live_checks:z.boolean().optional()}).strict()},async(a)=>wrap('scout_plan_job',async()=>{requireScope(connection,'profile:read');requireScope(connection,'profile:write');return callRpc('scout_plan_connection_job_v2',{p_connection_id:connection.connection_id,p_service_slug:a.service_slug,p_scheduled_start:a.scheduled_start,p_scheduled_end:a.scheduled_end??null,p_target:a.target,p_delivery_method_slug:a.delivery_method_slug??null,p_equipment:a.equipment??[],p_operating_plan:a.operating_plan??{},p_candidate_key:a.candidate_key??null,p_queue_live_checks:a.queue_live_checks??true})}))
  server.registerTool('scout_get_job_preflight',{title:'Get Scout Job Preflight',description:'Read a scoped job with separate static and live-operability state.',inputSchema:z.object({job_id:z.string().uuid()}).strict()},async({job_id})=>wrap('scout_get_job_preflight',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_job_preflight_v2',{p_connection_id:connection.connection_id,p_job_id:job_id})}))
  server.registerTool('scout_refresh_job_preflight',{title:'Refresh Scout Job Preflight',description:'Re-run static readiness and queue fresh permitted live checks.',inputSchema:z.object({job_id:z.string().uuid(),queue_live_checks:z.boolean().optional()}).strict()},async({job_id,queue_live_checks})=>wrap('scout_refresh_job_preflight',async()=>{requireScope(connection,'profile:read');requireScope(connection,'profile:write');return callRpc('scout_refresh_connection_job_preflight_v2',{p_connection_id:connection.connection_id,p_job_id:job_id,p_queue_live_checks:queue_live_checks??true})}))
  server.registerTool('scout_search_document_standards',{title:'Search Scout Document Standards',description:'Search document standards/exemplars using a bounded business/technical phrase.',inputSchema:z.object({query:z.string().min(1).max(300),domain:z.string().max(100).optional(),jurisdiction:z.string().max(40).optional(),criticality:z.enum(['routine','important','critical','gate']).optional(),limit:z.number().int().min(1).max(25).optional()}).strict()},async({query,domain,jurisdiction,criticality,limit})=>wrap('scout_search_document_standards',async()=>{requireScope(connection,'knowledge:read');return callRpc('search_document_standards',{p_query:query,p_domain:domain??null,p_jurisdiction:jurisdiction??null,p_criticality:criticality??null,p_limit:limit??10})}))
  server.registerTool('scout_get_document_standard',{title:'Get Scout Document Standard',description:'Retrieve one standard with blueprint, exemplars, requirements, guardrails, and currentness.',inputSchema:z.object({slug:shortMachineKey}).strict()},async({slug})=>wrap('scout_get_document_standard',async()=>{requireScope(connection,'knowledge:read');return callRpc('get_document_standard',{p_slug:slug})}))
  server.registerTool('scout_get_entry_brief',{title:'Get Scout Entry Brief',description:'Default bounded Scout business brief after critical onboarding.',inputSchema:z.object({limit:z.number().int().min(1).max(5).optional()}).strict()},async({limit})=>wrap('scout_get_entry_brief',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_entry_brief',{p_connection_id:connection.connection_id,p_limit:limit??null,p_include_opportunities:connection.scopes.includes('opportunities:read'),p_include_knowledge:connection.scopes.includes('knowledge:read')})}))
  server.registerTool('scout_get_alerts',{title:'Get Scout Alerts',description:'Read up to three current actionable Scout items on demand.',inputSchema:z.object({limit:z.number().int().min(1).max(3).optional()}).strict()},async({limit})=>wrap('scout_get_alerts',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_alerts_v2',{p_connection_id:connection.connection_id,p_limit:limit??3})}))
  server.registerTool('scout_get_entry_preferences',{title:'Get Scout Entry Preferences',description:'Read greeting/feed settings.',inputSchema:z.object({})},async()=>wrap('scout_get_entry_preferences',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_entry_preferences',{p_connection_id:connection.connection_id})}))
  server.registerTool('scout_update_entry_preferences',{title:'Update Scout Entry Preferences',description:'Update finite greeting/feed behavior.',inputSchema:z.object({patch:entryPreferencePatch}).strict()},async({patch})=>wrap('scout_update_entry_preferences',async()=>{requireScope(connection,'profile:write');return callRpc('scout_update_connection_entry_preferences_v2',{p_connection_id:connection.connection_id,p_patch:patch})}))
  server.registerTool('scout_update_entry_item',{title:'Update Scout Entry Item',description:'Dismiss, snooze, complete, reset, or mark a feed item opened.',inputSchema:z.object({item_key:z.string().min(3).max(300),action:z.enum(['dismiss','snooze','complete','reset','opened']),snooze_days:z.number().int().min(1).max(730).optional()}).strict()},async({item_key,action,snooze_days})=>wrap('scout_update_entry_item',async()=>{requireScope(connection,'profile:write');return callRpc('scout_record_connection_entry_action',{p_connection_id:connection.connection_id,p_item_key:item_key,p_action:action,p_snooze_days:snooze_days??null})}))
  server.registerTool('scout_list_onboarding_options',{title:'List Scout Onboarding Options',description:'Read requested service choices and relevant credential types without identifiers.',inputSchema:z.object({service_slugs:z.array(shortMachineKey).optional(),operating_states:z.array(z.string().regex(/^[A-Za-z]{2}$/)).optional()}).strict()},async({service_slugs,operating_states})=>wrap('scout_list_onboarding_options',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_onboarding_catalog',{p_service_slugs:service_slugs??null,p_operating_states:operating_states?.map(s=>s.toUpperCase())??null})}))
  server.registerTool('scout_search_equipment_models',{title:'Search Scout Equipment Catalog',description:'Resolve an operator-provided equipment model without serial numbers.',inputSchema:z.object({query:z.string().min(1).max(160),limit:z.number().int().min(1).max(30).optional()}).strict()},async({query,limit})=>wrap('scout_search_equipment_models',async()=>{requireScope(connection,'profile:read');const data=await callRpc('scout_search_equipment_models',{p_query:query,p_limit:limit??12});return{query,matches:data}}))
  server.registerTool('scout_get_privacy_summary',{title:'Get Scout Privacy Summary',description:'Explain connection access, privacy boundaries, retention, scopes, allowed tools, and contracts.',inputSchema:z.object({})},async()=>wrap('scout_get_privacy_summary',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_privacy_summary',{p_connection_id:connection.connection_id})}))
  server.registerTool('scout_list_external_capabilities',{title:'List External Capability Vocabulary',description:'Return Scout capability taxonomy and conservative known integration mappings.',inputSchema:z.object({domain:z.string().min(1).max(80).optional(),integration_name:z.string().min(1).max(160).optional()}).strict()},async({domain,integration_name})=>wrap('scout_list_external_capabilities',async()=>{requireScope(connection,'profile:read');let integrationKey:string|null=null;let resolutionResult:any=null;if(integration_name){resolutionResult=await callRpc('scout_resolve_external_integration',{p_name:integration_name});if(resolutionResult?.matched)integrationKey=resolutionResult.integration_key}const data=await callRpc('scout_get_external_capability_catalog',{p_domain:domain??null,p_integration_key:integrationKey});return integration_name?{resolution:resolutionResult,catalog:data}:data}))
  server.registerTool('scout_resolve_external_integration',{title:'Resolve Known External Integration',description:'Resolve a visible integration product name to conservative Scout capability mappings.',inputSchema:z.object({name:z.string().min(1).max(160)}).strict()},async({name})=>wrap('scout_resolve_external_integration',async()=>{requireScope(connection,'profile:read');return callRpc('scout_resolve_external_integration',{p_name:name})}))
  server.registerTool('scout_report_external_capabilities',{title:'Report Relevant Host Capabilities',description:'Report only Scout-relevant capability metadata already visible to the host agent.',inputSchema:z.object({capabilities:z.array(z.object({slug:shortMachineKey,availability:z.enum(['available','unavailable']).optional(),confidence:z.enum(['declared','mapped','inferred','suggested']).optional(),source_protocol:z.enum(['mcp','a2a','openapi','native','host_report','unknown']).optional(),integration_key:shortMachineKey.optional(),integration_label:z.string().max(160).optional(),tool_label:z.string().max(160).optional()}).strict()).max(100),replace:z.boolean().optional(),ttl_hours:z.number().int().min(1).max(720).optional()}).strict()},async({capabilities,replace,ttl_hours})=>wrap('scout_report_external_capabilities',async()=>{requireScope(connection,'profile:write');return callRpc('scout_report_external_capabilities',{p_connection_id:connection.connection_id,p_capabilities:capabilities,p_replace:replace??false,p_ttl_hours:ttl_hours??168})}))
  server.registerTool('scout_get_external_capabilities',{title:'Get Reported External Capabilities',description:'Return current capability metadata for this Scout connection.',inputSchema:z.object({include_unavailable:z.boolean().optional()}).strict()},async({include_unavailable})=>wrap('scout_get_external_capabilities',async()=>{requireScope(connection,'profile:read');return callRpc('scout_get_connection_external_capabilities',{p_connection_id:connection.connection_id,p_include_unavailable:include_unavailable??false})}))
  server.registerTool('scout_prepare_external_context_request',{title:'Prepare Minimal External Context Request',description:'Validate one reported external capability and return a minimized host instruction.',inputSchema:z.object({capability_slug:shortMachineKey,purpose_code:purposeCode,requested_fields:z.array(machineKey).min(1).max(25),scope:externalScope.optional()}).strict()},async({capability_slug,purpose_code,requested_fields,scope})=>wrap('scout_prepare_external_context_request',async()=>{requireScope(connection,'profile:read');return callRpc('scout_prepare_external_context_request_v2',{p_connection_id:connection.connection_id,p_capability_slug:capability_slug,p_purpose_code:purpose_code,p_requested_fields:requested_fields,p_scope:scope??{}})}))
  server.registerTool('scout_set_external_capability_consent',{title:'Set External Capability First-Use Choice',description:'Record the operator explicit first-use choice for one external capability/source.',inputSchema:z.object({capability_slug:shortMachineKey,source_key:z.string().min(3).max(300),action:z.enum(['grant','decline','disable','reset']),snooze_days:z.number().int().min(1).max(730).optional()}).strict()},async({capability_slug,source_key,action,snooze_days})=>wrap('scout_set_external_capability_consent',async()=>{requireScope(connection,'profile:write');return callRpc('scout_set_external_capability_consent',{p_connection_id:connection.connection_id,p_capability_slug:capability_slug,p_source_key:source_key,p_action:action,p_snooze_days:snooze_days??90})}))
  return server
},{maxRequestBodySize:MAX_BODY_BYTES})

function responseHeaders(h:Headers){h.set('access-control-allow-origin','*');h.set('vary','Origin');h.set('cache-control','no-store, max-age=0');h.set('pragma','no-cache');h.set('referrer-policy','no-referrer');h.set('x-content-type-options','nosniff');h.set('x-scout-privacy',PRIVACY_NOTICE_VERSION);h.set('x-scout-contract',CONTRACT_VERSION);h.set('x-scout-exposure-contract',EXPOSURE_CONTRACT_VERSION);h.set('x-scout-enumeration-contract',ENUMERATION_CONTRACT_VERSION);return h}
Deno.serve(async(req:Request)=>{
  const started=Date.now()
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:responseHeaders(new Headers({'access-control-allow-headers':'authorization,content-type,mcp-protocol-version,mcp-session-id,x-request-id','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'}))})
  const auth=req.headers.get('authorization')||'';const match=auth.match(/^Bearer\s+(.+)$/i)
  if(!match)return Response.json({error:'missing Scout bearer token'},{status:401,headers:responseHeaders(new Headers())})
  const token=match[1].trim();const {data,error}=await db.rpc('scout_resolve_agent_connection_v4',{p_token:token,p_privacy_contract:CONTRACT_VERSION,p_exposure_contract:EXPOSURE_CONTRACT_VERSION,p_enumeration_contract:ENUMERATION_CONTRACT_VERSION})
  if(error||!data)return Response.json({error:'invalid or expired Scout connection'},{status:401,headers:responseHeaders(new Headers())})
  const connection=data as Connection
  let raw=''
  try{const declared=Number(req.headers.get('content-length')||0);if(declared>MAX_BODY_BYTES)throw new Error('request_too_large');if(req.method==='POST')raw=await readBodyLimited(req.clone(),MAX_BODY_BYTES)}catch(e){const err=normalizeToolError(e);const pf:Preflight={ok:false,status:413,toolName:null,argumentKeys:[],flags:['request_too_large'],requestId:null,reason:'Scout tool request exceeds the privacy gateway size limit'};await audit(connection,pf,'rejected_privacy',MAX_BODY_BYTES+1,Date.now()-started,413);return Response.json({error:{...err,code:'request_too_large',message:pf.reason,retryable:false}},{status:413,headers:responseHeaders(new Headers())})}
  const requestBytes=new TextEncoder().encode(raw).byteLength;const pf=preflight(raw,connection)
  if(!pf.ok){await audit(connection,pf,'rejected_privacy',requestBytes,Date.now()-started,pf.status);return Response.json({error:{code:pf.status===400?'invalid_json':'privacy_boundary_rejected',message:pf.reason||'Scout request rejected',details:null,hint:null,validation_reason:pf.flags.join(', ')||null,retryable:false,diagnostic_id:crypto.randomUUID()},privacy_notice:PRIVACY_NOTICE_VERSION,contract:CONTRACT_VERSION},{status:pf.status,headers:responseHeaders(new Headers())})}
  const authInfo={token:'scout-connection-token-redacted',clientId:connection.connection_id,scopes:connection.scopes||[],expiresAt:connection.expires_at?Math.floor(new Date(connection.expires_at).getTime()/1000):undefined,extra:{connection}}
  try{const response=await mcp.fetch(req,{authInfo});await audit(connection,pf,response.status>=500?'error':'allowed',requestBytes,Date.now()-started,response.status);return new Response(response.body,{status:response.status,statusText:response.statusText,headers:responseHeaders(new Headers(response.headers))})}catch(e){await audit(connection,pf,'error',requestBytes,Date.now()-started,500);return Response.json({error:normalizeToolError(e)},{status:500,headers:responseHeaders(new Headers())})}
})
