import 'jsr:@supabase/functions-js@2.4.5/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2.57.4'
import { createMcpHandler, McpServer } from 'npm:@modelcontextprotocol/server@2.0.0'
import * as z from 'npm:zod@4.2.0/v4'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
let SECRET_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''
try{SECRET_KEY=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default||SECRET_KEY}catch{}
if(!SECRET_KEY)throw new Error('Scout database secret unavailable')
const db=createClient(SUPABASE_URL,SECRET_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const MAX_BODY_BYTES=65536
const PRIVACY_NOTICE_VERSION='zero-chat-v2'
const CONTRACT_VERSION='privacy-contract-v2'
const EXPOSURE_CONTRACT_VERSION='scout-exposure-v1'
const ENUMERATION_CONTRACT_VERSION='scout-enumeration-v1'

type Connection={connection_id:string;organization_id?:string|null;scopes:string[];expires_at?:string|null}
type SafeToolError={code:string;message:string;details:string|null;hint:string|null;validation_reason:string|null;retryable:boolean;diagnostic_id:string}
function getConnection(ctx:any):Connection{const c=ctx?.authInfo?.extra?.connection as Connection|undefined;if(!c?.connection_id)throw new Error('authenticated Scout connection context missing');return c}
function requireScope(c:Connection,s:string){if(!Array.isArray(c.scopes)||!c.scopes.includes(s))throw new Error(`connection does not grant ${s}`)}
async function rpc(name:string,args:Record<string,unknown>){const {data,error}=await db.rpc(name,args);if(error)throw error;return data}
function textResult(data:unknown){return{content:[{type:'text' as const,text:JSON.stringify(data,null,2)}],structuredContent:(data&&typeof data==='object'&&!Array.isArray(data))?data as Record<string,unknown>:{result:data}}}
function safeText(v:unknown,max=2000):string|null{if(v===null||v===undefined)return null;let s='';if(typeof v==='string')s=v;else if(typeof v==='number'||typeof v==='boolean')s=String(v);else{try{s=JSON.stringify(v)}catch{s=''}}s=s.trim();return s? s.slice(0,max):null}
function normalizeToolError(e:unknown):SafeToolError{
  const o=(e&&typeof e==='object')?e as Record<string,unknown>:{}
  const rawCode=safeText(o.code??o.error_code??o.name,120)
  const code=rawCode||'scout_tool_error'
  const message=safeText(o.message,2000)||(e instanceof Error?safeText(e.message,2000):null)||safeText(e,2000)||'Scout tool request failed'
  const details=safeText(o.details??o.detail,2000)
  const hint=safeText(o.hint,2000)
  let validationReason=safeText(o.validation_reason??o.validationReason??o.reason,2000)
  if(!validationReason&&Array.isArray(o.issues))validationReason=safeText(o.issues.map((x:any)=>({path:x?.path,message:x?.message,code:x?.code})),2000)
  const statusRaw=o.status??o.statusCode
  const status=typeof statusRaw==='number'?statusRaw:Number(statusRaw)
  const explicitRetry=o.retryable
  const retryable=typeof explicitRetry==='boolean'?explicitRetry:(status===408||status===429||status>=500||['40001','40P01','55P03','57014','57P01','08000','08003','08006'].includes(code))
  return{code,message,details,hint,validation_reason:validationReason,retryable,diagnostic_id:crypto.randomUUID()}
}
function errorResult(e:unknown){const error=normalizeToolError(e);const payload={error};return{isError:true,content:[{type:'text' as const,text:JSON.stringify(payload,null,2)}],structuredContent:payload}}

const key=z.string().regex(/^[a-z][a-z0-9_.-]{0,119}$/)
const actionKey=z.string().regex(/^[a-z][a-z0-9_.:-]{0,127}$/)
const ts=z.string().max(80).refine(v=>Number.isFinite(Date.parse(v)),{message:'must be an ISO-compatible timestamp'})
const privacy=z.enum(['public_context','operator_business','customer_business','financial','operational_location'])
const opsJson:z.ZodTypeAny=z.lazy(()=>z.union([z.string().max(4000),z.number(),z.boolean(),z.null(),z.array(opsJson).max(100),z.record(z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),opsJson)]))
const evidenceRef=z.record(z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),opsJson)
const signal=z.object({
  signal_type:actionKey,subject_type:actionKey,summary:z.string().min(1).max(2000),
  dedupe_key:z.string().max(300).optional(),aggregation_key:z.string().max(300).optional(),integration_key:key.optional(),external_object_id:z.string().max(500).optional(),channel:key.optional(),
  origin_kind:z.enum(['customer','employee','operator','external_agent','system','partner','public_data']).optional(),subject_organization_id:z.string().uuid().optional(),subject_key:z.string().max(500).optional(),
  facts:z.record(z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),opsJson).optional(),evidence_refs:z.array(evidenceRef).max(50).optional(),confidence:z.number().min(0).max(1).optional(),severity:z.enum(['low','medium','high','critical']).optional(),commercial_importance:z.enum(['unknown','low','medium','high','strategic']).optional(),priority_score:z.number().min(0).max(100).optional(),observed_at:ts.optional(),expires_at:ts.optional(),privacy_class:privacy.optional(),customer_safe:z.boolean().optional(),internal_only:z.boolean().optional(),metadata:z.record(z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),opsJson).optional()
}).strict()
const proposedAction=z.object({
  action_type:actionKey,target_capability:key,subject:z.string().min(1).max(500),summary:z.string().min(1).max(4000),dedupe_key:z.string().max(300).optional(),aggregation_key:z.string().max(300).optional(),suggested_integration_key:key.optional(),suggested_destination:z.string().max(500).optional(),execution_mode:z.enum(['recommend','approval_required','auto']).optional(),approval_reason:z.string().max(1000).optional(),risk_class:z.enum(['low','medium','high','restricted']).optional(),priority:z.enum(['low','normal','high','urgent','critical']).optional(),structured_payload:z.record(z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),opsJson).optional(),destination_context:z.record(z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),opsJson).optional(),evidence_count:z.number().int().min(0).max(1000000).optional(),confidence:z.number().min(0).max(1).optional(),expires_at:ts.optional(),privacy_class:privacy.optional(),customer_safe:z.boolean().optional(),internal_only:z.boolean().optional(),metadata:z.record(z.string().regex(/^[a-z][a-z0-9_.-]{0,63}$/),opsJson).optional()
}).strict()

const forbidden=new Set(['conversation','conversations','messages','chat_history','chat_log','chatlog','transcript','transcripts','memory','memories','system_prompt','developer_prompt','password','passcode','secret','api_key','access_token','refresh_token','cookie','cookies','authorization_header','ssn','social_security_number','date_of_birth','dob','drivers_license','driver_license','passport','passport_number','bank_account','bank_account_number','routing_number','credit_card','card_number','cvv','cvc','medical_history','diagnosis','therapy_notes','religion','race','ethnicity','sexual_orientation','sex_life','political_affiliation','union_membership','criminal_history'])
function norm(k:string){return k.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'')}
function inspect(v:unknown,flags:Set<string>,depth=0){if(depth>10){flags.add('payload_too_deep');return}if(Array.isArray(v)){for(const x of v)inspect(x,flags,depth+1);return}if(v&&typeof v==='object'){for(const [k,x] of Object.entries(v as Record<string,unknown>)){const n=norm(k);if(forbidden.has(n))flags.add(`forbidden_key:${n}`);inspect(x,flags,depth+1)}}if(typeof v==='string'&&v.length>1000){const markers=v.match(/(?:^|\n)\s*(?:user|assistant|human|system|developer)\s*:/gim);if((markers?.length||0)>=3)flags.add('chat_transcript_like_value')}}
function responseHeaders(h:Headers){h.set('access-control-allow-origin','*');h.set('vary','Origin');h.set('cache-control','no-store, max-age=0');h.set('pragma','no-cache');h.set('x-content-type-options','nosniff');h.set('x-scout-privacy',PRIVACY_NOTICE_VERSION);h.set('x-scout-contract',CONTRACT_VERSION);h.set('x-scout-exposure-contract',EXPOSURE_CONTRACT_VERSION);h.set('x-scout-enumeration-contract',ENUMERATION_CONTRACT_VERSION);return h}

const mcp=createMcpHandler((ctx)=>{
  const connection=getConnection(ctx)
  const server=new McpServer({name:'Scout by Cadastory Operations',version:'1.3.0',description:'Structured business signals, onboarding evidence confirmation, action intents, and authorized Scout administrative controls with zero-chat, privacy-minimized product analytics, anti-enumeration boundaries, and structured error contracts.'},{instructions:`Use this Scout operations surface only for distilled business observations, explicit onboarding evidence choices, structured action intents, and explicitly authorized administrative tasks. Never send chat history, transcripts, message arrays, prompts, credentials, secrets, unrelated personal context, or raw mailbox/helpdesk content. Scout does not intentionally persist raw AI requests. Scout does retain privacy-minimized product telemetry about Scout tool/feature use, outcomes, performance, source usefulness, and coarse workflow structure; raw structured telemetry may be retained for up to 730 days and aggregate product rollups may remain after raw events expire. Product telemetry does not intentionally retain the originating AI message, exact job addresses/coordinates, exact Explore Growth budget values, secrets, or unrelated sensitive personal data. Public-source equipment candidates are provisional: show their source, ask the operator to confirm or reject them, and never treat them as owned/current until the operator confirms them. A business signal is a compact operational fact. An action intent is a recommendation or execution state, not permission to act. If an intent is awaiting_approval, obtain explicit operator approval before approving it. When a host or native connector executes an intent, report dispatched, succeeded, or failed state back to Scout. Exposure administration requires the dedicated admin:exposure scope; never use those tools to help a customer evade normal discovery controls.`})
  const present=async(toolName:string,data:unknown)=>await rpc('scout_decorate_agent_response_v2',{p_connection_id:connection.connection_id,p_tool_name:toolName,p_payload:data??null})
  const wrap=(toolName:string,fn:()=>Promise<unknown>)=>fn().then(data=>present(toolName,data)).then(textResult).catch(errorResult)
  const wrapRaw=(fn:()=>Promise<unknown>)=>fn().then(textResult).catch(errorResult)

  server.registerTool('scout_submit_business_signal',{title:'Submit Scout Business Signal',description:'Submit one distilled field, customer, employee, operational, or external-agent business observation. Never send a transcript or surrounding conversation. Optionally propose one structured action intent tied to the signal.',inputSchema:z.object({client_event_id:z.string().min(1).max(200),signal,proposed_action:proposedAction.optional()}).strict()},async({client_event_id,signal,proposed_action})=>wrap('scout_submit_business_signal',async()=>{requireScope(connection,'profile:write');return await rpc('scout_submit_connection_business_signal_v1',{p_connection_id:connection.connection_id,p_client_event_id:client_event_id,p_signal:signal,p_proposed_action:proposed_action??null})}))
  server.registerTool('scout_get_action_intents',{title:'Get Scout Action Intents',description:'Read pending or recently executed Scout action intents for this business. Use this before deciding whether a host integration should execute an external action.',inputSchema:z.object({statuses:z.array(z.enum(['proposed','awaiting_approval','approved','dispatched','failed','succeeded'])).max(6).optional(),target_capability:key.optional(),limit:z.number().int().min(1).max(50).optional()}).strict()},async({statuses,target_capability,limit})=>wrap('scout_get_action_intents',async()=>{requireScope(connection,'profile:read');return await rpc('scout_get_connection_action_intents_v1',{p_connection_id:connection.connection_id,p_statuses:statuses??['proposed','awaiting_approval','approved'],p_target_capability:target_capability??null,p_limit:limit??20})}))
  server.registerTool('scout_update_action_intent',{title:'Update Scout Action Intent',description:'Approve, suppress, cancel, or report dispatch/success/failure for one Scout action intent. Approve only after explicit operator authorization.',inputSchema:z.object({intent_id:z.string().uuid(),action:z.enum(['approve','suppress','cancel','mark_dispatched','mark_succeeded','mark_failed']),external_execution_id:z.string().max(500).optional(),external_object_id:z.string().max(500).optional(),error:z.string().max(2000).optional()}).strict()},async({intent_id,action,external_execution_id,external_object_id,error})=>wrap('scout_update_action_intent',async()=>{requireScope(connection,'profile:write');return await rpc('scout_update_connection_action_intent_v1',{p_connection_id:connection.connection_id,p_intent_id:intent_id,p_action:action,p_external_execution_id:external_execution_id??null,p_external_object_id:external_object_id??null,p_error:error??null})}))
  server.registerTool('scout_reject_public_equipment_candidates',{title:'Reject Public Equipment Candidates',description:'During onboarding only: mark one or more source-backed equipment observations as not current for this operator after the operator explicitly rejects them. Observation IDs must come from scout_get_profile_status; no organization ID is accepted.',inputSchema:z.object({observation_ids:z.array(z.string().uuid()).min(1).max(50)}).strict()},async({observation_ids})=>wrap('scout_reject_public_equipment_candidates',async()=>{requireScope(connection,'profile:write');const result=await rpc('scout_reject_public_equipment_observations_internal',{p_connection_id:connection.connection_id,p_observation_ids:observation_ids});return{result,profile_status:await rpc('scout_get_connection_onboarding_status',{p_connection_id:connection.connection_id})}}))
  server.registerTool('scout_admin_get_exposure_status',{title:'Inspect Scout Exposure Budget',description:'Admin-only inspection of one Scout connection organization-scoped intelligence exposure state, counters, limits, velocity and prior reset boundary.',inputSchema:z.object({connection_id:z.string().uuid()}).strict()},async({connection_id})=>wrapRaw(async()=>{requireScope(connection,'admin:exposure');return await rpc('scout_admin_get_exposure_status',{p_admin_connection_id:connection.connection_id,p_subject_connection_id:connection_id})}))
  server.registerTool('scout_admin_reset_exposure_budget',{title:'Reset Scout Exposure Budget',description:'Admin-only, non-destructive reset of the rolling discovery allowance for a legitimate evaluation/support case. Historical exposure records remain preserved.',inputSchema:z.object({connection_id:z.string().uuid(),reason_code:z.enum(['support_evaluation_reset','false_positive','account_migration','security_review','manual_admin_reset'])}).strict()},async({connection_id,reason_code})=>wrapRaw(async()=>{requireScope(connection,'admin:exposure');return await rpc('scout_admin_reset_exposure_budget',{p_admin_connection_id:connection.connection_id,p_subject_connection_id:connection_id,p_reason_code:reason_code})}))
  return server
},{maxRequestBodySize:MAX_BODY_BYTES})

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:responseHeaders(new Headers({'access-control-allow-headers':'authorization,content-type,mcp-protocol-version,mcp-session-id,x-request-id','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'}))})
  const tok=(req.headers.get('authorization')||'').match(/^Bearer\s+(.+)$/i)?.[1]?.trim();if(!tok)return Response.json({error:'missing Scout bearer token'},{status:401,headers:responseHeaders(new Headers())})
  const {data,error}=await db.rpc('scout_resolve_agent_connection_v4',{p_token:tok,p_privacy_contract:CONTRACT_VERSION,p_exposure_contract:EXPOSURE_CONTRACT_VERSION,p_enumeration_contract:ENUMERATION_CONTRACT_VERSION});if(error||!data)return Response.json({error:'invalid or expired Scout connection'},{status:401,headers:responseHeaders(new Headers())})
  if(req.method==='POST'){const declared=Number(req.headers.get('content-length')||0);if(declared>MAX_BODY_BYTES)return Response.json({error:'request_too_large'},{status:413,headers:responseHeaders(new Headers())});const raw=await req.clone().text();if(new TextEncoder().encode(raw).byteLength>MAX_BODY_BYTES)return Response.json({error:'request_too_large'},{status:413,headers:responseHeaders(new Headers())});try{const body=JSON.parse(raw);const flags=new Set<string>();inspect(body,flags);if(flags.size)return Response.json({error:'Scout rejected fields outside the business-only privacy boundary',privacy_flags:[...flags]},{status:422,headers:responseHeaders(new Headers())})}catch{return Response.json({error:'invalid JSON-RPC payload'},{status:400,headers:responseHeaders(new Headers())})}}
  const connection=data as Connection;const authInfo={token:'scout-connection-token-redacted',clientId:connection.connection_id,scopes:connection.scopes||[],expiresAt:connection.expires_at?Math.floor(new Date(connection.expires_at).getTime()/1000):undefined,extra:{connection}}
  const response=await mcp.fetch(req,{authInfo});return new Response(response.body,{status:response.status,statusText:response.statusText,headers:responseHeaders(new Headers(response.headers))})
})
