import 'jsr:@supabase/functions-js/edge-runtime.d.ts'
import { createClient } from 'npm:@supabase/supabase-js@2.57.4'

const SLUG='collect-household-site-organization-evidence'
const SEARCH='https://api.tavily.com/search'
const db=createClient(Deno.env.get('SUPABASE_URL')!,serviceKey(),{auth:{persistSession:false,autoRefreshToken:false}})
const BLOCKED=['facebook.com','linkedin.com','instagram.com','x.com','twitter.com','yelp.com','bbb.org','mapquest.com','yellowpages.com','bizapedia.com','zoominfo.com','manta.com','chamberofcommerce.com','loc8nearme.com','restaurantguru.com','craft.co','cience.com','seamless.ai','rocketreach.co','aeroleads.com','opencorporates.com','wikipedia.org']

type O=Record<string,any>
type Job={id:string;search_query?:string|null;context?:O}
type Match={name:string;website:string;sourceUrl:string;sourceAuthority:string;confidence:number;excerpt:string;attributes:O}

function serviceKey(){try{const k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default;if(k)return k}catch{}const k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!k)throw new Error('Scout database credentials unavailable');return k}
function response(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}})}
function err(v:unknown){return String(v instanceof Error?v.message:v).replace(/Bearer\s+[\w.-]+/gi,'Bearer [REDACTED]').replace(/tvly-[\w-]+/g,'[REDACTED]').replace(/sb_secret_[\w-]+/g,'[REDACTED]').slice(0,1000)}
function domain(u:string){try{return new URL(u).hostname.toLowerCase().replace(/^www\./,'')}catch{return''}}
function blocked(u:string){const d=domain(u);return !d||BLOCKED.some(x=>d===x||d.endsWith(`.${x}`))}
function sameSite(a:string,b:string){const x=domain(a),y=domain(b);return !!x&&!!y&&(x===y||x.endsWith(`.${y}`)||y.endsWith(`.${x}`))}
function normText(v:string){return String(v||'').toUpperCase().normalize('NFKD').replace(/[^A-Z0-9# ]+/g,' ').replace(/\s+/g,' ').trim()}
function normStreet(v:string){let s=normText(v).replace(/\b(SUITE|STE|UNIT|APT|APARTMENT)\b.*$/,'').trim();const map:Record<string,string>={STREET:'ST',ROAD:'RD',AVENUE:'AVE',BOULEVARD:'BLVD',HIGHWAY:'HWY',PARKWAY:'PKWY',PKY:'PKWY',DRIVE:'DR',LANE:'LN',COURT:'CT',PLACE:'PL',TRACE:'TRCE',TRAIL:'TRL',TERRACE:'TER',CIRCLE:'CIR',NORTH:'N',SOUTH:'S',EAST:'E',WEST:'W'};s=s.split(' ').map(x=>map[x]||x).join(' ');return s.replace(/\s+/g,' ').trim()}
function normName(v:string){return normText(v).replace(/\b(INCORPORATED|INC|CORPORATION|CORP|COMPANY|CO|LLC|LTD)\b/g,'').replace(/\s+/g,' ').trim()}
function types(v:any):string[]{const x=v?.['@type'];return Array.isArray(x)?x.map(String):x?[String(x)]:[]}
function organizationalType(ts:string[]){return ts.some(t=>/(Organization|Business|Corporation|Store|Restaurant|School|College|University|Church|Synagogue|Mosque|Temple|Hospital|Medical|Government|CivicStructure|Place)/i.test(t))&&!ts.some(t=>/^Person$/i.test(t))}
function flatten(v:any,out:any[]=[]):any[]{if(Array.isArray(v)){for(const x of v)flatten(x,out);return out}if(v&&typeof v==='object'){out.push(v);if(v['@graph'])flatten(v['@graph'],out)}return out}
function jsonLd(html:string){const out:any[]=[];for(const m of html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){const raw=m[1].trim();if(!raw)continue;try{flatten(JSON.parse(raw),out)}catch{}}return out}
function addresses(node:any){const out:any[]=[];const add=(v:any)=>{if(Array.isArray(v))v.forEach(add);else if(v&&typeof v==='object')out.push(v)};add(node?.address);if(node?.location&&typeof node.location==='object')add(node.location.address);return out}
function addressMatch(a:any,ctx:O){const street=normStreet(String(a?.streetAddress||'')),want=normStreet(String(ctx.site_address_text||''));if(!street||!want||street!==want)return false;const region=normText(String(a?.addressRegion||'')),wantRegion=normText(String(ctx.state_code||''));if(region&&wantRegion&&region!==wantRegion&&region!==({KY:'KENTUCKY',IN:'INDIANA',OH:'OHIO'} as O)[wantRegion])return false;const locality=normText(String(a?.addressLocality||'')),wantCity=normText(String(ctx.city||''));if(locality&&wantCity&&locality!==wantCity)return false;return true}
function pageExcerpt(node:any,a:any){return JSON.stringify({type:types(node),name:node?.name||null,url:node?.url||null,address:{streetAddress:a?.streetAddress||null,addressLocality:a?.addressLocality||null,addressRegion:a?.addressRegion||null,postalCode:a?.postalCode||null}}).slice(0,1800)}

async function fetchHtml(u:string){if(blocked(u)||/\.(pdf|docx?|xlsx?)(\?|$)/i.test(u))return null;const r=await fetch(u,{redirect:'follow',signal:AbortSignal.timeout(10000),headers:{accept:'text/html,application/xhtml+xml;q=0.9,*/*;q=0.5','user-agent':'Scout-by-Cadastory/1.0 site-organization-evidence'}});if(!r.ok)return null;const ct=r.headers.get('content-type')||'';if(!/html|xhtml/i.test(ct))return null;const html=(await r.text()).slice(0,1500000);return{url:r.url||u,html}}

async function search(job:Job,key:string|null,mode:string){const headers:Record<string,string>={'content-type':'application/json'};if(key)headers.authorization=`Bearer ${key}`;else if(mode==='keyless')headers['x-tavily-access-mode']='keyless';else throw new Error('search provider unavailable');const r=await fetch(SEARCH,{method:'POST',signal:AbortSignal.timeout(12000),headers,body:JSON.stringify({query:job.search_query,topic:'general',search_depth:'basic',max_results:8,include_answer:false,include_raw_content:false,include_images:false})});const raw=await r.text();if(!r.ok)throw new Error(`search provider HTTP ${r.status}: ${raw.slice(0,250)}`);const b=JSON.parse(raw);return Array.isArray(b?.results)?b.results:[]}

async function inspect(job:Job,key:string|null,mode:string):Promise<Match[]>{const results=await search(job,key,mode),ctx=job.context||{},matches:Match[]=[];for(const x of results){const u=String(x?.url||''),score=Number(x?.score??0);if(!u||score<.35||blocked(u))continue;const p=await fetchHtml(u);if(!p||blocked(p.url))continue;for(const node of jsonLd(p.html)){const ts=types(node);if(!organizationalType(ts))continue;const name=String(node?.name||'').trim();if(!name||name.length<2)continue;const nodeUrl=String(node?.url||'').trim();if(nodeUrl&&/^https?:\/\//i.test(nodeUrl)&&!sameSite(nodeUrl,p.url))continue;for(const a of addresses(node)){if(!addressMatch(a,ctx))continue;const website=nodeUrl&&/^https?:\/\//i.test(nodeUrl)?nodeUrl:`${new URL(p.url).origin}/`;matches.push({name,website,sourceUrl:p.url,sourceAuthority:`First-party structured organization site (${domain(p.url)})`,confidence:.97,excerpt:pageExcerpt(node,a),attributes:{address_match_basis:'exact_first_party_structured_address',structured_types:ts,structured_name:name,structured_url:nodeUrl||null,street_address:a?.streetAddress||null,address_locality:a?.addressLocality||null,address_region:a?.addressRegion||null,postal_code:a?.postalCode||null,search_result_score:score,acquisition_transport:'supabase_edge',search_provider:mode==='keyless'?'tavily_keyless':'tavily'}})}}}
  const dedupe=new Map<string,Match>();for(const m of matches){const k=normName(m.name);if(!k)continue;const old=dedupe.get(k);if(!old||m.confidence>old.confidence)dedupe.set(k,m)}return[...dedupe.values()]
}

async function complete(job:Job,outcome:string,m:Match|null,error:string|null=null){const r=await db.rpc('internal_complete_household_site_organization_job_v1',{p_job_id:job.id,p_outcome:outcome,p_organization_name:m?.name||null,p_website_url:m?.website||null,p_source_url:m?.sourceUrl||null,p_source_authority:m?.sourceAuthority||null,p_identity_confidence:m?.confidence||null,p_evidence_excerpt:m?.excerpt||null,p_attributes:m?.attributes||{},p_error:error});if(r.error)throw new Error(`completion: ${r.error.message}`);return r.data}
async function authorized(req:Request){const k=req.headers.get('x-scout-key')||'';if(!k)return false;const r=await db.rpc('internal_validate_collector_key',{p_key:k});return!r.error&&r.data===true}
async function begin(limit:number){const r=await db.rpc('internal_begin_collector_run',{p_slug:SLUG,p_request_summary:{limit,resolution_scope:'household_site_organization'}});if(r.error||!r.data)throw new Error('collector run could not be recorded');return String(r.data)}
async function finish(id:string,status:'succeeded'|'failed'|'no_work',http:number,summary:O){const r=await db.rpc('internal_finish_collector_run',{p_run_id:id,p_status:status,p_http_status:http,p_summary:summary});if(r.error)throw new Error('collector result could not be recorded')}

Deno.serve(async req=>{if(req.method!=='POST')return response({error:'POST required'},405);if(!await authorized(req))return response({error:'unauthorized'},401);const raw=await req.text();if(new TextEncoder().encode(raw).byteLength>32768)return response({error:'request_too_large'},413);let body:O={};try{body=JSON.parse(raw||'{}')}catch{return response({error:'invalid_json'},400)}const limit=Math.max(1,Math.min(8,Number(body.limit)||4));let run='';try{run=await begin(limit);const pc=await db.rpc('internal_get_buyer_research_provider_v1');if(pc.error)throw new Error(`provider config: ${pc.error.message}`);const mode=String(pc.data?.mode||((pc.data?.configured===true&&typeof pc.data?.api_key==='string')?'api_key':'disabled'));const key=typeof pc.data?.api_key==='string'&&pc.data.api_key?String(pc.data.api_key):null;const available=pc.data?.search_available===true||mode==='api_key'||mode==='keyless';const c=await db.rpc('internal_claim_household_site_organization_jobs_v1',{p_limit:limit,p_search_available:available});if(c.error)throw new Error(`claim: ${c.error.message}`);const jobs:Job[]=Array.isArray(c.data)?c.data:[];const provider=mode==='keyless'?'tavily_keyless':mode==='api_key'?'tavily':'disabled';if(!jobs.length){const s={outcome:'no_work',counts:{attempted:0,succeeded:0,failed:0},provider};await finish(run,'no_work',200,s);return response({ok:true,outcome:'no_work',run_id:run,claimed:0,processed:[],provider})}const processed:O[]=[];for(const job of jobs){try{const ms=await inspect(job,key,mode);let result:unknown;if(ms.length===0)result=await complete(job,'no_evidence',null,'no exact-address first-party structured organization evidence found');else if(ms.length>1)result=await complete(job,'needs_review',null,`multiple first-party structured organizations match site address (${ms.length})`);else result=await complete(job,'completed',ms[0]);processed.push({job_id:job.id,status:'succeeded',match_count:ms.length,result})}catch(e){const m=err(e);try{processed.push({job_id:job.id,status:'succeeded',worker_error:m,result:await complete(job,'failed',null,m)})}catch(e2){throw new Error(`${m}; failure completion also failed: ${err(e2)}`)}}}const s={outcome:'succeeded',counts:{attempted:jobs.length,succeeded:processed.length,failed:0},provider};await finish(run,'succeeded',200,s);return response({ok:true,outcome:'succeeded',run_id:run,claimed:jobs.length,processed,provider})}catch(e){const m=err(e);if(run)try{await finish(run,'failed',500,{outcome:'failed',counts:{attempted:null,succeeded:null,failed:1},errors:[m]})}catch{};console.error(m);return response({ok:false,outcome:'failed',run_id:run||null,error:m},500)}})