create or replace function public.scout_get_component_sandbox_asset_v1_internal(p_opportunity_type text)
returns jsonb language sql stable security definer set search_path to 'pg_catalog' as $function$
with chosen as(
 select o.* from scout.opportunity_search_spine o
 where (p_opportunity_type='bridge' and o.source_kind='bridge' and o.signal_kind='bridge_condition_or_inspection' and o.details->>'structure_number'='037B00052R')
 or (p_opportunity_type='construction_site' and o.source_kind='construction_window' and o.signal_kind='construction_lifecycle' and o.details->>'address'='700 CENTRAL AVE' and o.details->>'project_type'='Commercial Alteration')
 or (p_opportunity_type='dam' and o.source_kind='dam_condition_cadence' and o.signal_kind='dam_condition' and o.display_name='Hurricane Lake Dam' and o.details->>'county'='Nelson' and o.state_code='KY')
 or (p_opportunity_type='mine_quarry' and o.source_kind='active_mine' and o.signal_kind='mine_material_activity' and o.candidate_key='mine:1200013')
 or (p_opportunity_type='landfill' and o.source_kind='landfill' and o.signal_kind='landfill_capacity_gas' and o.display_name='Nelson County SWDF' and o.details->>'county'='Nelson' and o.state_code='KY')
 or (p_opportunity_type='rail_crossing' and o.source_kind='rail_crossing_context' and o.signal_kind='rail_crossing_risk' and o.candidate_key='rail_crossing:724527H')
 or (p_opportunity_type='roof_lifecycle' and o.source_kind='roof_lifecycle' and o.signal_kind='roof_lifecycle' and lower(o.display_name)='831 e broadway' and o.details->>'anchor_date'='2006-09-15')
 or (p_opportunity_type='solar_lifecycle' and o.source_kind='solar_lifecycle' and o.signal_kind='solar_lifecycle' and o.candidate_key='solar_lifecycle:69741')
 order by o.refreshed_at desc nulls last,o.observed_at desc nulls last limit 1
), rel as(
 select jsonb_build_array(jsonb_build_object('candidate_key',f.candidate_key,'source_kind',f.source_kind,'signal_kind',f.signal_kind,'summary',f.why_now,'confidence',f.confidence)) v
 from scout.opportunity_search_spine f where p_opportunity_type='bridge' and f.source_kind='funded_pain' and f.signal_kind='bridge_condition_or_planned_work' and f.why_now ilike 'Bridge 037B00052R%'
 order by f.refreshed_at desc nulls last limit 1
)
select jsonb_build_object(
 'contract_version','spine_single_asset_map_v1','opportunity_type',p_opportunity_type,'candidate_key',o.candidate_key,'source_kind',o.source_kind,'signal_kind',o.signal_kind,
 'display_name',o.display_name,'status_label',case p_opportunity_type when 'bridge' then 'Bridge condition signal' when 'construction_site' then 'Construction lifecycle signal' when 'dam' then 'Dam condition signal' when 'mine_quarry' then 'Active mine / quarry signal' when 'landfill' then 'Landfill capacity / gas signal' when 'rail_crossing' then 'Rail crossing context signal' when 'roof_lifecycle' then 'Roof lifecycle signal' when 'solar_lifecycle' then 'Solar lifecycle signal' end,
 'signal_strength',o.signal_strength,'confidence',o.confidence,'observed_at',o.observed_at,'time_sensitive',o.time_sensitive,'why_now',o.why_now,
 'location_label',case p_opportunity_type when 'construction_site' then o.details->>'address' when 'rail_crossing' then pg_catalog.concat_ws(', ',o.details->>'city',o.state_code) when 'roof_lifecycle' then o.display_name else pg_catalog.concat_ws(', ',o.county_name,o.state_code) end,
 'site_point',jsonb_build_object('lon',extensions.st_x(o.location::extensions.geometry),'lat',extensions.st_y(o.location::extensions.geometry),'geometry_type','Point','semantics','source_opportunity_point'),
 'target',jsonb_build_object('target_class',o.target_class,'resolution_status',o.target_resolution_status,'name',coalesce(o.target_name,o.display_name)),
 'buyer',jsonb_build_object('resolution_status',coalesce(o.buyer_resolution_status,'unresolved'),'name',o.buyer_name,'contact_status',coalesce(o.buyer_contact_status,'unresolved'),'procurement_status',coalesce(o.procurement_status,'unresolved')),
 'facts',case p_opportunity_type
  when 'bridge' then jsonb_build_array(jsonb_build_object('label','Structure','value',o.details->>'structure_number'),jsonb_build_object('label','Condition','value',o.details->>'effective_condition_band'),jsonb_build_object('label','Inspection','value',o.details->>'inspection_date'),jsonb_build_object('label','Owner','value',coalesce(o.buyer_name,o.details->>'owner_class')),jsonb_build_object('label','Planned work','value',coalesce((select r.v->0->>'summary' from rel r),'No separate planned-work signal attached')))
  when 'construction_site' then jsonb_build_array(jsonb_build_object('label','Address','value',o.details->>'address'),jsonb_build_object('label','Project type','value',o.details->>'project_type'),jsonb_build_object('label','Stage','value',o.details->>'current_stage'),jsonb_build_object('label','Project value','value',pg_catalog.concat('$',pg_catalog.to_char((o.details->>'project_value')::numeric,'FM999,999,999,990'))),jsonb_build_object('label','Project area','value',pg_catalog.concat(pg_catalog.to_char((o.details->>'square_feet')::numeric,'FM999,999,990'),' sq ft')),jsonb_build_object('label','Contractor','value',o.details->>'contractor_name'))
  when 'dam' then jsonb_build_array(jsonb_build_object('label','Condition','value',o.details->>'condition_assessment'),jsonb_build_object('label','Last inspection','value',o.details->>'last_inspection_date'),jsonb_build_object('label','Hazard potential','value',o.details->>'hazard_potential'),jsonb_build_object('label','Inspection cadence','value',pg_catalog.concat(o.details->>'inspection_frequency_years',' years')),jsonb_build_object('label','Regulator','value',o.details->>'state_regulatory_agency'))
  when 'mine_quarry' then jsonb_build_array(jsonb_build_object('label','Mine type','value',o.details->>'mine_type'),jsonb_build_object('label','Status','value',o.details->>'status_raw'),jsonb_build_object('label','Commodity','value',o.details->>'commodity_text'),jsonb_build_object('label','Operator','value',o.details->>'operator_name'))
  when 'landfill' then jsonb_build_array(jsonb_build_object('label','Status','value','Open landfill'),jsonb_build_object('label','Waste in place','value',pg_catalog.concat(pg_catalog.to_char((o.details->>'waste_in_place_tons')::numeric,'FM999,999,999,990'),' tons')),jsonb_build_object('label','Closure year','value',o.details->>'closure_year'),jsonb_build_object('label','Owner','value',o.details->>'owner'),jsonb_build_object('label','Gas collection','value',case when (o.details->>'gas_collection_system')::boolean then 'Recorded system present' else 'No recorded system' end))
  when 'rail_crossing' then jsonb_build_array(jsonb_build_object('label','Crossing','value','724527H'),jsonb_build_object('label','Street','value',o.details->>'street'),jsonb_build_object('label','Railroad','value',o.details->>'railroad_name'),jsonb_build_object('label','Road traffic','value',pg_catalog.concat(o.details->>'annual_avg_daily_traffic',' AADT')),jsonb_build_object('label','Train movements','value',pg_catalog.concat(o.details->>'trains_day',' / day')),jsonb_build_object('label','Timetable speed','value',pg_catalog.concat(o.details->>'max_timetable_speed',' mph')))
  when 'roof_lifecycle' then jsonb_build_array(jsonb_build_object('label','Lifecycle band','value',o.details->>'lifecycle_band'),jsonb_build_object('label','Approx. age','value',pg_catalog.concat(o.details->>'age_years_estimate',' years')),jsonb_build_object('label','Age anchor','value',o.details->>'anchor_date'),jsonb_build_object('label','Date precision','value',o.details->>'date_precision'),jsonb_build_object('label','Replacement history','value','Corroboration required'))
  when 'solar_lifecycle' then jsonb_build_array(jsonb_build_object('label','Plant','value',o.details->>'plant_name'),jsonb_build_object('label','Capacity','value',pg_catalog.concat(o.details->>'capacity_mw',' MW')),jsonb_build_object('label','Lifecycle','value',o.details->>'lifecycle_state'),jsonb_build_object('label','Status code','value',o.details->>'status_code'),jsonb_build_object('label','Planned operation','value',o.details->>'planned_operation_date'),jsonb_build_object('label','Entity','value',o.details->>'entity_name')) end,
 'related_signals',coalesce((select r.v from rel r),'[]'::jsonb),
 'guardrail',case p_opportunity_type when 'bridge' then 'Bridge condition, inspection cadence, and separately documented planned-work evidence support qualification only. Scout is not making a structural-engineering determination. A plan signal is not proof that work is funded, currently procuring, accessible, or available to a drone operator.' when 'construction_site' then 'The permit record supports a newly permitted construction-lifecycle signal. Stage is inferred from permit status and timing, not observed field progress. This does not prove a drone scope, active procurement, site access, buyer intent, or work availability.' when 'dam' then 'Authoritative condition and inspection-cadence records support investigation only. Scout is not making a dam-safety determination, declaring an inspection legally due, or asserting procurement, access, owner intent, or work availability.' when 'mine_quarry' then 'Current operating status and commodity context support inspection, mapping, or volumetric qualification. They do not prove a measurement request, recurring service cadence, procurement, safe site access, or authorization to enter or operate at the mine.' when 'landfill' then 'Landfill capacity, closure, and gas-system context support investigation only. They do not establish a current inspection need, methane-service need, procurement, buyer intent, site access, or authorization to operate.' when 'rail_crossing' then 'FRA crossing characteristics support account and inspection research; they are not a real-time incident alert or proof of maintenance need. The point does not define railroad property, right-of-way, safe operating airspace, access permission, or authorization to work near rail operations.' when 'roof_lifecycle' then 'The permit issue date is only an approximate original-building/roof age anchor. Scout does not know whether the roof was replaced later and is not asserting current roof condition, replacement need, procurement, buyer intent, access, or work availability.' when 'solar_lifecycle' then 'EIA lifecycle timing supports O&M and inspection qualification. It does not establish a defect, commissioning task, cleaning need, procurement, site access, interconnection status beyond the cited record, or work availability.' end
) from chosen o where extensions.st_geometrytype(o.location::extensions.geometry)='ST_Point';
$function$;
revoke all on function public.scout_get_component_sandbox_asset_v1_internal(text) from public,anon,authenticated;
grant execute on function public.scout_get_component_sandbox_asset_v1_internal(text) to service_role;
